### ISSUE TITLE
New to Go

### ISSUE THREAD

**Issue by kutysam** [andygrunwald/go-jira#108]
I know this isn't the right place to ask this question as it isn't an issue.

However, i hope you guys can assist me.

How do i create a component to be tagged to a createissue?

`	i := jira.Issue{
		Fields: &jira.IssueFields{
			Assignee: &jira.User{
				Name: "sample",
			},
			Reporter: &jira.User{
				Name: "samplereporter",
			},
			Components: &[]jira.Component{{Name: "testcomponent"}},
			Project: jira.Project{
				Key: "PROJTEST",
			},
`

I'm lost as to how to initialise Components. Hope someone here can assist me.

**Comment by rbriski** [comment]
You can look at this project for a good example of how to create an issue with a component:
https://github.com/jshirley/slack-ask/

Specifically, this function shows how to do it.
https://github.com/jshirley/slack-ask/blob/master/asker/jira.go#L31

**Comment by andygrunwald** [comment]
@kutysam Does the comment by @rbriski help?

**Comment by rbriski** [comment]
@kutysam , I'm going to close this.  Tell me if you need more help.
