### ISSUE TITLE
Cookie-based auth and basic auth with password to be deprecated on Jira cloud APIs - start using API tokens 

### ISSUE THREAD

**Issue by mansilladev** [andygrunwald/go-jira#116]
See: https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-basic-auth-and-cookie-based-auth/

As of March 15, 2018, in accordance to the [Atlassian REST API Policy](https://developer.atlassian.com/platform/marketplace/atlassian-rest-api-policy/), support for **passwords in HTTP basic auth** requests and **cookie-based authentication** will no longer be supported on or after September 15, 2018.

Instead of passwords, you should start using [API tokens](https://confluence.atlassian.com/cloud/api-tokens-938839638.html).

**Comment by rbriski** [comment]
Thanks.  I'll be sure to include that in the authentication library that I'm building.  It's actually separate from the main `go-jira` library.  `go-jira` doesn't handle authentication directly.  It accepts an `http.Client` that does the authentication.  

I'll update and close this issue when I have working code.

**Comment by mansilladev** [comment]
For basic auth, you just need to replace the password with an API token, and it will work exactly the same. If the library uses cookie-based auth, you’ll need to switch to either OAuth 1.0a or basic.

**Comment by rbriski** [comment]
That's simple enough. I'll update the docs

**Comment by ghostsquad** [comment]
@andygrunwald is this complete, or still needs to be done?

**Comment by andygrunwald** [comment]
@ghostsquad Seems to be done. @rbriski added the note to the readme here: https://github.com/andygrunwald/go-jira/commit/485b3ca79ce92959c39e4319476650189fc8b364

@rbriski @mansilladev If you disagree, let us know. We will reopen this ticket.

**Comment by DylanGraham** [comment]
Would you mind keeping basic auth?
It's still useful for Jira Server users who cannot create API tokens without a paid plugin: https://marketplace.atlassian.com/apps/1221182/api-tokens-for-jira?hosting=server&tab=overview
Thanks
