### ISSUE TITLE
Data is not an array, custom field create jira issue

### ISSUE THREAD

**Issue by lwoj17** [andygrunwald/go-jira#117]
I'm trying to create a new issue in Jira using a custom field and continue to receive this error:

{"errorMessages":[],"errors":{"This Field":"data was not an array"}}
This:  Request failed. Please analyze the request body for more details. Status code: 400

The test code:

```
func main() {                                                       
    client, err := connectJira()                                    
    if err != nil {                                                 
        fmt.Println("error:", err)                                  
        return                                                      
    }                                                               
                                                                    
    i := jira.Issue{                                                
        Fields: &jira.IssueFields{                                  
            Assignee: &jira.User{                                   
                Name: "username",                                   
            },                                                      
            Description: "SOME_DESCRIPTION",                        
            Type: jira.IssueType{                                   
                Self: "http://jiraisthebest/rest/api/2/issuetype/3",
                Name: "Task",                                       
            },                                                      
            Unknowns: tcontainer.MarshalMap{                        
                "customfield_11882": "SOMEVALUE",                   
            },                                                      
            Project: jira.Project{                                  
                Key: "ITW",                                         
            },                                                      
            Summary: "Just a demo issue",                           
        },                                                          
    }                                                               
    issue, response, err := client.Issue.Create(&i)                 
    body, readErr := ioutil.ReadAll(response.Body)                  
    if readErr != nil {                                             
        fmt.Println("Body error:", readErr)                         
        return                                                      
    }                                                               
    fmt.Println(string(body))                                       
    if err != nil {                                                 
        fmt.Println("This: ", err)                                  
        return                                                      
    }                                                               
                                                                    
    fmt.Printf("%s: %+v\n", issue.Key, issue.Fields.Summary)        
}                                                                   

```

**Comment by rbriski** [comment]
Can you try this construction?

https://github.com/kortheof/golang-exercises/blob/0f87123ceabf4b36a77dcb7ffff284011e3c09b4/Jira_Spreadsheets/createJira.go#L23

**Comment by lwoj17** [comment]
This didn't work either. I think this has to do with the custom field being a 'multi-select field'..

**Comment by rbriski** [comment]
Have you tried reading the issue and inspecting what is returned?

**Comment by rbriski** [comment]
@lwoj17 can you use `httputil.DumpResponse` to show the full response from the client?

**Comment by lwoj17** [comment]
@rbriski sorry I have been absent on this. I will give `httputil.DumpResponse` a try today. A little update since last time.. New code `func main() {                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                         
    customfield_11882 := tcontainer.NewMarshalMap()                                                                                                                                                                                                                                                                                                                                                                                      
    customfield_11882["value"] = "Linux"                                                                                                                                                                                                                                                                                                                                                                                                 
    client, err := connectJira()                                                                                                                                                                                                                                                                                                                                                                                                         
    if err != nil {                                                                                                                                                                                                                                                                                                                                                                                                                      
        fmt.Println("I CANT CONNECTO TO JIRA error:", err)                                                                                                                                                                                                                                                                                                                                                                               
        return                                                                                                                                                                                                                                                                                                                                                                                                                           
    }                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                         
    i := jira.Issue{                                                                                                                                                                                                                                                                                                                                                                                                                     
        Fields: &jira.IssueFields{                                                                                                                                                                                                                                                                                                                                                                                                       
            Description: "Test Description",                                                                                                                                                                                                                                                                                                                                                                                             
            Type: jira.IssueType{                                                                                                                                                                                                                                                                                                                                                                                                        
                Name: "Task",                                                                                                                                                                                                                                                                                                                                                                                                            
            },                                                                                                                                                                                                                                                                                                                                                                                                                           
            Project: jira.Project{                                                                                                                                                                                                                                                                                                                                                                                                       
                Key: "ITW",                                                                                                                                                                                                                                                                                                                                                                                                              
            },                                                                                                                                                                                                                                                                                                                                                                                                                           
            Summary:  "Just a demo issue",                                                                                                                                                                                                                                                                                                                                                                                               
            Unknowns: customfield_11882,                                                                                                                                                                                                                                                                                                                                                                                                 
        },                                                                                                                                                                                                                                                                                                                                                                                                                               
    }                                                                                                                                                                                                                                                                                                                                                                                                                                    
    issue, response, err := client.Issue.Create(&i)                                                                                                                                                                                                                                                                                                                                                                                      
    fmt.Println(response)                                                                                                                                                                                                                                                                                                                                                                                                                
    body, readErr := ioutil.ReadAll(response.Body)                                                                                                                                                                                                                                                                                                                                                                                       
    if readErr != nil {                                                                                                                                                                                                                                                                                                                                                                                                                  
        fmt.Println("Body error:", readErr)                                                                                                                                                                                                                                                                                                                                                                                              
        return                                                                                                                                                                                                                                                                                                                                                                                                                           
    }                                                                                                                                                                                                                                                                                                                                                                                                                                    
    fmt.Println(string(body))                                                                                                                                                                                                                                                                                                                                                                                                            
    if err != nil {                                                                                                                                                                                                                                                                                                                                                                                                                      
        fmt.Println("Error: ", err)                                                                                                                                                                                                                                                                                                                                                                                                      
        return                                                                                                                                                                                                                                                                                                                                                                                                                           
    }                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                         
    fmt.Printf("%s: %+v\n", issue.Key, issue.Fields.Summary)                                                                                                                                                                                                                                                                                                                                                                             
`

And error response: 
{"errorMessages":[],"errors":{"value":"Field 'value' cannot be set. It is not on the appropriate screen, or unknown."}}
Error:  Request failed. Please analyze the request body for more details. Status code: 400

the editmeta on this issue shows:

    "customfield_11882": {
      "required": true,
      "schema": {
        "type": "array",
        "items": "option",
        "custom": "com.atlassian.jira.plugin.system.customfieldtypes:multicheckboxes",
        "customId": 11882
      },
      "name": "Teams",
      "operations": [
        "add",
        "set",
        "remove"
      ],

**Comment by lwoj17** [comment]
@rbriski I believe this is what you are asking for?

`*jira.Response Request failed. Please analyze the request body for more details. Status code: 400                            
HTTP/1.1 400                                                                                                                 
Transfer-Encoding: chunked                                                                                                   
Cache-Control: no-cache, no-store, no-transform                                                                              
Content-Type: application/json;charset=UTF-8                                                                                 
Date: Thu, 19 Apr 2018 18:14:47 GMT                                                                                          
Set-Cookie: JSESSIONID=0D450E67CDE0D3D110E070FDA03F64E3;path=/;HttpOnly                                                      
Set-Cookie: atlassian.xsrf.token=AYQC-EXZP-1EW1-N9UI|2c5961d7aba659e09d3f3dd5fa7138dca9801432|lin;path=/                     
X-Arequestid: 794x3856969x2                                                                                                  
X-Asen: SEN-3330345                                                                                                          
X-Asessionid: 1rcvpw1                                                                                                        
X-Ausername: svc_account                                                                                                 
X-Content-Type-Options: nosniff                                                                                              
X-Seraph-Loginreason: OK                                                                                                     
                                                                                                                             
7d                                                                                                                           
{"errorMessages":[],"errors":{"Teams":"Field 'Teams' cannot be set. It is not on the appropriate screen, or unknown."}}`

I had to get the *http.Response from:
`issue, response, err := client.Issue.Create(&i)             
fmt.Println(reflect.TypeOf(response), err)                  
                                                            
dump, err := httputil.DumpResponse(response.Response, true) 
if err != nil {                                             
    fmt.Println("Error1: ", err)                            
    return                                                  
}                                                           
                                                            
fmt.Println(string(dump))                                   
`

**Comment by lwoj17** [comment]
This is the full output of editmeta

```    "customfield_11882": { 
      "required": true,
      "schema": {
        "type": "array",
        "items": "option",
        "custom": "com.atlassian.jira.plugin.system.customfieldtypes:multicheckboxes",
        "customId": 11882
      },
      "name": "Teams",
      "operations": [
        "add",
        "set",
        "remove"
      ],
      "allowedValues": [
        {
          "self": "http://jira/rest/api/2/customFieldOption/12060",
          "value": "Team 1",
          "id": "12060"
        },
        {
          "self": "http://jira/rest/api/2/customFieldOption/13902",
          "value": "Team 2",
          "id": "13902"
        }
      ]
    },
```
