### ISSUE TITLE
Parsing issue.Fields.Created and issue.Fields.Updated?

### ISSUE THREAD

**Issue by edwinakatosh** [andygrunwald/go-jira#118]
Having trouble parsing created and updated fields into time.

`2018-02-13T23:52:54.000-0600`

currently getting .. with my efforts

`0001-01-01 00:00:00.000000`

How can I parse? Any help is appreciated.

**Comment by rbriski** [comment]
That format is called ISO8601.  Golang (and most other languages) can parse it.

https://play.golang.org/p/xe2mWIHZGU

**Comment by rbriski** [comment]
That format is ISO8601 and I don't believe that Golang can parse it natively.  You have to actually give it a format to parse.  This shows how:
https://github.com/joeshaw/iso8601/blob/master/iso8601.go

I wouldn't include the library.  You just need the format string for parsing.

**Comment by rbriski** [comment]
You know what, I actually don't like the library I mentioned above.   Here's a quick way to do it:

https://play.golang.org/p/w0aBhNlm8ga

It uses `time.Parse`:
https://golang.org/pkg/time/#Parse

**Comment by edwinakatosh** [comment]
Thank you! I'll try that.
