### ISSUE TITLE
Expose the base JIRA URL

### ISSUE THREAD

**Issue by Kegsay** [andygrunwald/go-jira#12]
It's frustrating that the very base URL passed into the constructor for a `jira.Client` doesn't get exposed in some way. The URL is extremely useful when forming HTML links, and I'm continually having to pass a wrapper struct of `{ Client, BaseURL }`.

I fully understand why you *don't* want it to be **modified** from under you, but exposing a getter like `Client.BaseURL()` would be incredibly helpful for me.

**Comment by andygrunwald** [comment]
Thank you @Kegsay.
`c.GetBaseURL()` will return now a copy of the base url. Will this work for you?

**Comment by Kegsay** [comment]
That's great, thank you! Very prompt response :)
