### ISSUE TITLE
Error: unknown field 'BaseURL' in struct literal of type jira.CookieAuthTransport

### ISSUE THREAD

**Issue by BattleBas** [andygrunwald/go-jira#124]
In README.md the examples for **Create an issue** and **Call a not implemented API endpoint**, the type `CookieAuthTransport` is being passed the field `BaseURL` and then used by calling `tp.BaseUrl`.

When I try to do this I get the following error: 
`unknown field 'BaseURL' in struct literal of type jira.CookieAuthTransport`
Checking `type CookieAuthTransport struct` in jira.go, I don't see the field BaseURL, was this removed at some point?

Is this by design and has the README just not being updated? Or is this something else?
Thank you!

Snippet of code example below highlighting the use case:
```go
tp := jira.CookieAuthTransport{
	Username: "username",
	Password: "password",
	BaseURL:  "https://my.jira.com",
}

jiraClient, err := jira.NewClient(tp.Client(), tp.BaseURL)
```

**Comment by rbriski** [comment]
Yeah, the documentation is incorrect.  Look at this example for the actual behavior: https://github.com/andygrunwald/go-jira#authenticate-with-session-cookie

I'll update the documentation to reflect the actual behavior.  

As a side note, cookie auth is not recommended.  If you want the simplest way to access JIRA, it's best to use basic auth: https://github.com/andygrunwald/go-jira#basic-auth-example.  Of course, I don't know your use case so...

**Comment by BattleBas** [comment]
Thank you for the response, using basic auth works fine for what I'm doing.

Maybe mentioning your recommendation to use basic auth in the documentation might be a good idea?

**Comment by rbriski** [comment]
I've updated the docs and added your logo in #127 .  Thanks!
