### ISSUE TITLE
Documentation with Time

### ISSUE THREAD

**Issue by tormath1** [andygrunwald/go-jira#128]
Hi, thanks for this lib. :smile: 

However, I would like to get `updated` field from a Jira issue, but I don't know how to get it. 

```go
if err = issue.Fields.Updated.UnmarshalJSON(???????????)); err != nil {
    log.Fatalf(err.Error())
}
```

What do we need to use as `UnmarshalJSON` arg ? 
Thanks !

**Comment by rbriski** [comment]
Yeah, this took me a little bit to figure out.  You have to cast it to a `time.Time` before you can operate on the value.
```go
updated := time.Time(issue.Fields.Updated)
fmt.Println(updated.String())
```

You can also output an alternative format with the `Format` function: https://golang.org/pkg/time/#Time.Format

**Comment by tormath1** [comment]
Awesome. Thanks for the very quick response !
