### ISSUE TITLE
BUG: requests fail if baseUrl contains extra path

### ISSUE THREAD

**Issue by shdunning** [andygrunwald/go-jira#129]
For Jira Server instances the base urls can contain extra path params (like https://example.com/jira) and `NewRequest` calls end up losing the last path param due to the way the request urls are built using `ResolveReference`:

https://github.com/andygrunwald/go-jira/blob/master/jira.go#L82
https://github.com/andygrunwald/go-jira/blob/master/jira.go#L119
https://github.com/andygrunwald/go-jira/blob/master/jira.go#L187

I *think* it should be safe to assume that the base urls are understood by developer and we should be keeping those intact and appending the relative url strings -- something like:

```
	rel, err := url.Parse(urlStr)
	if err != nil {
		return nil, err
	}

	u := path.Join(c.baseURL.String(), url.String())
```

The above will handle with or without preceding slashes in the relative url but won't handle crazy cases that [`ResolveReference` takes care of](https://golang.org/pkg/net/url/#example_URL_ResolveReference) -- not sure that all that defensive programming is necessary, tbh.

I'll submit a proposed bugfix today and see what you think.

**Comment by shdunning** [comment]
Never mind -- I misunderstood how baseUrls and relative urls are handled by `url.ResolveReference`. In this case, we need to make sure the stored baseUrl always has a trailing `/` and subsequent API calls use relative paths without the preceding slash (what the comments suggestion).

**Comment by andygrunwald** [comment]
Great that you solved it yourself.
If you think, we should simplify it by adding a slash to the URL once no one is there, feel free to apply a PR.

**Comment by andygrunwald** [comment]
> I can whip up a PR and we can discuss pros / cons.

Thank you!
