### ISSUE TITLE
Allow plug-ins to be added as a service

### ISSUE THREAD

**Issue by rbriski** [andygrunwald/go-jira#135]
The PR at #133 is trying to add a plugin API.  I like the idea of being able to harness `go-jira` with plug ins but I don't think it belongs in the core library.  This issue is to discuss notation around how to import and add a new service into `go-jira`.

**Comment by andygrunwald** [comment]
Looks like a quite simple solution :)

**Comment by rbriski** [comment]
After thinking about it a little, my solution wouldn't work.  I'm thinking of structs as objects, which they are definitely not.  The functions don't come along with `jira.Client`.  

You have actually already [highlighted a way to do it in the docs](https://github.com/andygrunwald/go-jira#call-a-not-implemented-api-endpoint)

**Comment by rbriski** [comment]
Closing because there is already a way to do it.  I've linked to it above.
