### ISSUE TITLE
Support of custom fields while creating issue

### ISSUE THREAD

**Issue by ashakabra** [andygrunwald/go-jira#136]
Hi , I am trying to create issue using custom fields ,

below JSON allows me to create issue through rest api
{  
   "fields":{  
      "project":{  
         "key":"ABC"
      },
      "summary":"TEST",
      "description":"Story is created from TEST",
      "issuetype":{  
         "name":"Story"
      },
      "customfield_10024" :{
    	"id" :"10036"
      }
   }
}

Could you please help in syntax of adding custom field to below code.
*********
jiraClient, err := jira.NewClient(nil, "https://your.jira-instance.com/")
if err != nil {
    panic(err)
}

res, err := jiraClient.Authentication.AcquireSessionCookie("username", "password")
if err != nil || res == false {
    fmt.Printf("Result: %v\n", res)
    panic(err)
}

customfield_10024 := tcontainer.NewMarshalMap()
customfield_10024["id"] = "10036"
i := jira.Issue{
    Fields: &jira.IssueFields{
        Assignee: &jira.User{
            Name: "myuser",
        },
        Reporter: &jira.User{
            Name: "youruser",
        },
        Description: "Test Issue",
        Type: jira.IssueType{
            Name: "Bug",
        },
        Project: jira.Project{
            Key: "PROJ1",
        },
        Summary: "Just a demo issue",
        Unknowns: customfield_10024,
    },
}
issue, _, err := jiraClient.Issue.Create(&i)
if err != nil {
    panic(err)
}

*********

P.S : I referred #35 as well, but I could not understand.

**Comment by rbriski** [comment]
Can you check out #117 and see if that helps you?

**Comment by andygrunwald** [comment]
Maybe we should add this to the docs.

**Comment by Jozrael** [comment]
Agreed! Just swinging by this for the first time and custom fields are definitely the first stumbling block to adoption. Thanks :).

**Comment by Jozrael** [comment]
In terms of getting custom fields working at all, I think you're really close @ashakabra. Possibly you just need to treat the map as the group of custom fields (even if you're only using one) - notably, where you used "id" for your key, that's where I needed to put the customfield's #. Like so:

```customfields := tcontainer.NewMarshalMap()
customfields["customfield_10631"] = "value you want to store!"
i := jira.Issue{
	Fields: &jira.IssueFields{
		Description: "Test Issue",
		Unknowns: customfields,
	},
}
issue, resp, err := c.TicketClient.Issue.Create(&i)```

Would work if customfield_10631 was the field you cared about.

**Comment by Jozrael** [comment]
My next question here is how to handle more esoteric types of custom fields, like User Pickers. E.g. "customfield_11425":"data was not an object" when trying to provide a string to a User Picker. Not sure how to package that up to go-jira just yet, but will take a look.

**Comment by rbriski** [comment]
I'm going to close this.  If there are additional questions we can reopen.

**Comment by kevincantu** [comment]
Yes, I really want a way to make custom fields from the cli!

**Comment by kevincantu** [comment]
The best I can do today is paste this into the YAML edit:
```yaml
fields:
  project: SAMPLE
...
assignee:
  emailAddress: me@example.test
customfield_999:
  id: "99999"
```
I find that doing that, helpful errors appear when you get the id wrong (this is a struct field with name / id).
