### ISSUE TITLE
Support renderedFields expand parameter

### ISSUE THREAD

**Issue by sleeper** [andygrunwald/go-jira#138]
Hi,

Great library, but would be greater if it was supporting the `renderedFields` expand option. This would help for example to retrieve comments formatted as HTML, instead of formatted as Wiki markup, and having to transform them ;)

**Comment by rbriski** [comment]
We'll put it on the list.  We're also very appreciative of code contributions :)

**Comment by sleeper** [comment]
Great! Regarding contributions let me think about it ;)
Seems like some regression that have been introduced in JIRA API related to that: https://jira.atlassian.com/browse/JRASERVER-65922

Where I'm a little bit worried, is that it will somehow need some form a introspection to iterate over the fields, find the non null ones and keep either the field coming from `fields` or from `renderedFields`.
