### ISSUE TITLE
Jira - Create project

### ISSUE THREAD

**Issue by gaurav218** [andygrunwald/go-jira#140]
Hi,

I have a requirement to automate project creation in Jira via terraform. Below are my use cases

1. create new project
2. add role to project (r/w/a)
3. remove role from project
4. delete project

Can you pl. help me here on how to do this as current version of your go library doesn't support these use cases. Do you have code snippets for create project ?

**Comment by rbriski** [comment]
You can go a couple of ways here.
### 1. Add the functionality to `go-jira` and open a PR
This is always great because others will be able to use your code

### 2. Just call a custom endpoint through `go-jira`
The README has instructions on [how to call endpoints that haven't yet been implemented](https://github.com/andygrunwald/go-jira#call-a-not-implemented-api-endpoint).  
The endpoint docs are pretty easy to find on the JIRA development site.  Here's the one for [creating a project.](https://developer.atlassian.com/cloud/jira/platform/rest/#api-api-2-project-post)

**Comment by gaurav218** [comment]
I have installed local Jira trail version and also terraform standalone setup in my system. 
Also installed jira CLI and my objective is to run remote-exec to call jira api commands like create project. 
I have configured environment variables like user, password, jira url etc and copied jira provider binary too. 
Can we call jira cli from remote-exec inline command via terraform ...if yes how to set it up and test

**Comment by rbriski** [comment]
This project is not a CLI.  It's a library.  I'm not super familiar with how terraform plugins work but you could:
1. Write your own CLI using this library
2. Include this library in the plugin system (I believe terraform is also written in go) and use terraform's own plugin API
3. Use a CLI that already uses this library (I think @andygrunwald actually wrote one)

**Comment by fourplusone** [comment]
Hi @gaurav218 I think you can do this with my fork of the terraform jira provider. Right now, its implemented in the provider itself, however in the longer run, this feature should be ported to go-jira :)

https://github.com/fourplusone/terraform-provider-jira

**Comment by ghostsquad** [comment]
Terraform and CLI bits aside, I think it would be useful to create a project. I'm just not sure how useful it would be within a library like this. That seems like a task that doesn't happen much.

**Comment by andygrunwald** [comment]
This project focus on being a library to implement into other projects.
We don't aim to provide a CLI.

If you are looking for a Jira CLI, check out https://github.com/go-jira/jira.

If you are looking for a Jira Terraform provider, check out these:
- https://github.com/fourplusone/terraform-provider-jira
- https://github.com/anubhavmishra/terraform-provider-jira

Thanks for the request, but this is not a feature we consider for this library.
