### ISSUE TITLE
Can't cast WorklogRecord.Created to time.Time

### ISSUE THREAD

**Issue by MaksymSv** [andygrunwald/go-jira#153]
Guys,

I have a struct:
```
type Worklog struct {
	Date      time.Time `json:"date"`
	TimeSpent int       `json:"timeSpent"`
	IssueKey  string    `json:"issueKey"`
}
```
and simple mapper that is not working (real code is different but shows the same situation):
```
	jw := jira.Worklog{}
	w := Worklog{}
	w.Date = jw.Worklogs[0].Started
```
Compilation error: **cannot use jw.Worklogs[0].Started (type jira.Time) as type time.Time in assignment**

jira.Time also doesn't have any formatting methods. How it supposed to be exposed to external code?

**Comment by rbriski** [comment]
Yeah, this is a little confusing.  I talked about it in #128 .

Try casting it to time.Time:
```golang
jw := jira.Worklog{}
w := Worklog{}
w.Date = time.Time(jw.Worklogs[0].Started)
```
