### ISSUE TITLE
Authentication incorrect in jira.go:NewClient

### ISSUE THREAD

**Issue by oddietaco** [andygrunwald/go-jira#162]
In `func NewClient(httpClient *http.Client, baseURL string) (*Client, error)` in `jira.go`, it appears that the client's authentication information is not being set.

I'm using this code, which is based off of the examples you document.

```
package main

import (
	"fmt"
	"strings"
	jira "github.com/andygrunwald/go-jira"
)

func main() {
	jiraURL := "https://mycompany.atlassian.net"
	username := "myemailaddress@somewhere.com"
	password := "myapikeyfromjira"

	tp := jira.BasicAuthTransport{
		Username: strings.TrimSpace(username),
		Password: strings.TrimSpace(password),
	}

	client, err := jira.NewClient(tp.Client(), strings.TrimSpace(jiraURL))
	if err != nil {
		fmt.Printf("\nerror: %v\n", err)
		return
	}

	i := jira.Issue{
		Fields: &jira.IssueFields{
			Assignee: &jira.User{
				Name: "myemailaddress@somewhere.com",
			},
			Reporter: &jira.User{
				Name: "myemailaddress@somewhere.com",
			},
			Description: "Test Issue",
			Type: jira.IssueType{
				Name: "Action Item",
			},
			Project: jira.Project{
				Key: "QC",
			},
			Summary: "Just a demo issue",
		},
	}
	issue, _, err := client.Issue.Create(&i)
	if err != nil {
		panic(err)
	}

	fmt.Printf("%s: %+v\n", issue.Key, issue.Fields.Summary)
}
```

I've stepped through the script using GoLand's debugger. Inspecting `c.Authentication` after it has been set shows that

* `authType = 0`
* `username = ""`
* `password = ""`

I have attached a screenshot from the debugger.

![2018-08-20_15-36-06](https://user-images.githubusercontent.com/1521583/44362619-8eed6000-a48f-11e8-8883-041600b1e2b5.png)

**Comment by rbriski** [comment]
Yeah, I should be clearer about the `AuthenticationService` being deprecated.  I try to call it out here:
https://github.com/andygrunwald/go-jira/blob/master/authentication.go#L96

Anyway, we've tried to switch away from authentication being handled by the API.  The standard is to let auth be handled by the http client and then letting that client be passed in when created the API client.  The code you initially quote does just that.

You can get the actual username/password combo if you want to dig around in the HTTP client but I don't think you really need to do that.  Is your code not authenticating correctly?

**Comment by oddietaco** [comment]
It works correctly for this code:

```
	searchOptions := &jira.SearchOptions{StartAt: 0, MaxResults: 100}
	issues, response, err := client.Issue.Search("status = Closed AND attachments is not EMPTY AND status changed to Closed before -90d ", searchOptions )
	if err != nil {
		panic(err)
	}
	if response.StatusCode != 200 {
		fmt.Println( "Response Code: " + response.Status)
		bodyBytes, _ := ioutil.ReadAll(response.Body)
		fmt.Println( "Body: " + string(bodyBytes) )
		return
	}

	fmt.Println("Issues: ")

	for _, issue := range issues {
		fmt.Println("   " + issue.ID + ": " + issue.Key)
	}
```

but not for this code
```
	i := jira.Issue{
		Fields: &jira.IssueFields{
			Assignee: &jira.User{
				Name: "myemailaddress@somewhere.com",
			},
			Reporter: &jira.User{
				Name: "myemailaddress@somewhere.com",
			},
			Description: "Test Issue",
			Type: jira.IssueType{
				Name: "Action Item",
			},
			Project: jira.Project{
				Key: "QC",
			},
			Summary: "Just a demo issue",
		},
	}
	issue, _, err := client.Issue.Create(&i)
	if err != nil {
		panic(err)
	}

	fmt.Printf("%s: %+v\n", issue.Key, issue.Fields.Summary)
```

I have attempted to create a ticket manually, using the exact same fields as the script does. It works to manually create the ticket, but it doesn't work in the script.
