### ISSUE TITLE
There is no support for pages in responses

### ISSUE THREAD

**Issue by nebril** [andygrunwald/go-jira#17]
go-github wraps http.Response with it's own struct, https://github.com/google/go-github/blob/master/github/github.go#L247 , which has paging-related attributes.

Pagination in JIRA API is described here: https://developer.atlassian.com/confdev/confluence-server-rest-api/pagination-in-the-rest-api

**Comment by nebril** [comment]
It seems that I linked to confluence docs, will try to find JIRA docs for paging.

**Comment by andygrunwald** [comment]
#18 was merged. Thanks a lot!
