### ISSUE TITLE
Project.Roles doesn't support roles other than "Developers"

### ISSUE THREAD

**Issue by Weiss91** [andygrunwald/go-jira#174]
I wanted to get list of all roles in a specific project.
These roles are customized in each jira instance. The existing version of this api does only support the role "Developers".
So i changed the project struct to make the roles field unmarshal customized project roles in a map.
This gives the caller the flexibility to check which roles are present in a project.
I also added a test to check if all given roles in mocks/project.json are unmarshalled in the map.
https://github.com/andygrunwald/go-jira/compare/master...Weiss91:master

Do you think this would be a reasonable representation of the data?
This is my first PR, i would be happy to get some feedback on how to improve. :)

**Comment by rbriski** [comment]
@Weiss91 Can you create a real PR?  It will be easier to work with.  We'll be able to review it and you can make changes in the same branch and they'll show up in the PR.  

Your test is a little confusing.  Why would there be 9 and not some other number of roles (or projects)?

**Comment by ghostsquad** [comment]
Fixed in #176
