### ISSUE TITLE
Allow to create an Issue with CustomFields when they are required fields

### ISSUE THREAD

**Issue by vtomasr5** [andygrunwald/go-jira#178]
Hi,

I've been trying to create an Issue but when I created a custom field in the "create issue form" and I don't specify those fields in the Issue struct I get an status code 400.

It has already support for that functionality? If so, how can I make it work? If not, how hard is to add it? ;)

Thanks

BTW good job!!

**Comment by SciGno** [comment]
I was wondering the same thing.  Maybe a function to add a custom fields to jira.IssueFields would be nice.

**Comment by ghostsquad** [comment]
Ya, I was trying to dig into the Godocs a bit to find this out too. there's an `Unknowns` field in the `IssueFields` struct. I tried doing something like this:

```
Unknowns: map[string]interface{}{
  "customfield_26902": "FOO",
},
```

but I get this error:
```
"errors\":{\"customfield_26902\":\"Could not find valid 'id' or 'value' in the Parent Option object.\"
```

The jira API documentation shows something that would be very difficult to implement in Go.

https://developer.atlassian.com/server/jira/platform/jira-rest-api-examples/

```
{
    "fields": {
       "project":
       {
          "key": "TEST"
       },
       "summary": "Always do right. This will gratify some people and astonish the REST.",
       "description": "Creating an issue while setting custom field values",
       "issuetype": {
          "name": "Bug"
       },       
       "customfield_11050" : "Value that we're putting into a Free Text Field."
   }
}
```

Allowing for strongly typed field names + custom fields is a problem. So I think this library is doing something different to make this work.

**Comment by ghostsquad** [comment]
Definitely on the write path I found out. The value depends on the customfield type explained here:

https://developer.atlassian.com/server/jira/platform/jira-rest-api-examples/

So this works if the field is jsut text:

```
Unknowns: map[string]interface{}{
  "customfield_26902": "FOO",
},
```

**Comment by ghostsquad** [comment]
This issue is stale. I'll be closing this in 14 days unless someone mentions it should remain open.

**Comment by stefanmcshane** [comment]
```
cf := tcontainer.NewMarshalMap()
// Adding a string custom field
cf["customfield_1234"] = "test"

// Multiselect selection
cf["customfield_1235"] = []map[string]string{{"value": "testvalue"}}

// Single select dropdown
cf["customfield_1236"] = map[string]string{{"value": "anothertestvalue"}

issue := jira.Issue{
     Fields: &jira.IssueFields{
	Unknowns:   t.CustomFields,
    },
}
```

Something along these lines work for me

**Comment by grantholly** [comment]
What is t (`t.CustomFields`) is the above example?

**Comment by andygrunwald** [comment]
@grantholly `t. CustomFields` should be https://github.com/andygrunwald/go-jira/blob/ef6d633ae18b202f9fcec03f5dd13eb806d779dd/issue.go#L552

**Comment by stefanmcshane** [comment]
Apologies - this is from a struct I had written and pulled out of.

We have had success using map[string]string, and tcontainer.NewMarshalMap(), which is used inside the jira library itself.

https://github.com/andygrunwald/go-jira/blob/ef6d633ae18b202f9fcec03f5dd13eb806d779dd/issue.go#L20

**Comment by grantholly** [comment]
Here's what I ended up using that worked.
```
        summary := "fun snail facts"
        cf := tcontainer.NewMarshalMap()
        cf["customfield_11700"] = "my custom field"

        i := jira.Issue{
                Fields: &jira.IssueFields{
                        Summary:     summary,
                        Description: "email snail facts",
                        Type: jira.IssueType{
                                Name: "Task",
                        },
                        Project: jira.Project{
                                Key: "project key",
                        },
                        Labels: []string{
                                "jokes", "snail-facts",
                        },
                        Unknowns: cf,
                },
        }
```
