### ISSUE TITLE
FilterService GetList method fails

### ISSUE THREAD

**Issue by davidnewman** [andygrunwald/go-jira#189]
The FilterService has a function named GetList defined in filter.go. This method doesn't work because it isn't a valid request in the JIRA API.

If you look at the official JIRA API docs: https://docs.atlassian.com/software/jira/docs/api/REST/7.12.0/?_ga=2.180696935.155455041.1542750289-2108505718.1535680562#api/2/filter

You can see that `api/2/filter` is not a valid request. Instead, you can either get a specific filter by ID or get the list of filters that are "favourites" of the user.

I have a PR I am about to open that adds a `GetFavouriteList` function.

**Comment by ghostsquad** [comment]
@davidnewman Can you create a PR that removes the method `GetList` that doesn't work?
