### ISSUE TITLE
How to create an issue with watchers added

### ISSUE THREAD

**Issue by wlmost** [andygrunwald/go-jira#191]
I am wondering how I can create an issue with given watchers.
That is my code
```go
	var issueWatcher []*jira.Watcher
	for _, w := range data.Watchers {
		var watcher = &jira.Watcher{
			Name: w,
		}
		issueWatcher = append(issueWatcher, watcher)
	}

	var issueWatches = jira.Watches{
		Watchers: issueWatcher,
	}

	var issue = jira.Issue{
		Fields: &jira.IssueFields{
			Assignee:    &jira.User{Name: data.Assignee},
			Reporter:    &jira.User{Name: data.Reporter},
			Project:     jira.Project{Key: data.Project},
			Summary:     data.Summary,
			Description: data.Description,
			Type:        jira.IssueType{Name: data.IssueType},
			Watches:     &issueWatches,
		},
	}
```
But I get following error:
```
Error: Issue could not created: Request failed. Please analyze the request body for more details. Status code: 400
```
Could you provide an example?

**Comment by ghostsquad** [comment]
@wlmost can you add the following to your code so you can get the request body and actual error coming from Jira?

```
body, _ := ioutil.ReadAll(resp.Body)
fmt.Println(string(body))
```

I suspect you can't add watchers until _after_ an issue is created.

**Comment by wlmost** [comment]
Sorry for the delay.
This is the error which i get
`
{"errorMessages":[],"errors":{"watches":"Field 'watches' cannot be set. It is not on the appropriate screen, or unknown."}}
`

**Comment by nealajpatel** [comment]
Also running into this issue :(

**Comment by andygrunwald** [comment]
Sadly, I don't have the time to look into it right now.
Until this is fixed in the library, have a look at https://community.atlassian.com/t5/Answers-Developer-Questions/Please-Help-Got-error-400-when-trying-to-add-watcher-using-REST/qaq-p/567259

There is a curl request that seems to work.
This can be combined then with https://github.com/andygrunwald/go-jira#call-a-not-implemented-api-endpoint

Hope this helps.

**Comment by ghostsquad** [comment]
Think of the same flow you would have to do through the UI. You usually can't add watchers during issue creation unless it's part of the "Create" screen (which I'm honestly not sure is possible, as I've never personally seen it).

So, the answer would be to create the issue then add watchers.

@wlmost I don't believe that what you are asking for is an issue with this library, but rather a limitation of either:

1. The JIRA API
2. The specific project/issue workflow you are using

I'm going to close this issue for now. If you feel this has been closed in error, please don't hesitate to reach back out.

**Comment by 030** [comment]
@ghostsquad please reopen this ticket as the trying to update the watchers once the ticket has been created does not work either

**Comment by benjivesterby** [comment]
@030 are you able to make it work using the `curl` command against your project? If so please let us know. 

@ghostsquad is correct that normally only fields available in the specific screen (create,edit,update) are available to the api when performing that specific function. 

Can you please verify that you are able to add watchers during ticket creation in the UI?

**Comment by 030** [comment]
@benjivesterby Yes. It just worked. I used the v2 and the username should contain double quotes, see:

https://community.atlassian.com/t5/Answers-Developer-Questions/Please-Help-Got-error-400-when-trying-to-add-watcher-using-REST/qaq-p/567259

**Comment by benjivesterby** [comment]
@030 the link you provided is using a URL which contains the ticket key which means it's only usable after ticket creation.

**Comment by 030** [comment]
@benjivesterby That is true.

**Comment by 030** [comment]
@benjivesterby updating watchers does not seem to work either. Should a different ticket be created or could this one reopened?

**Comment by benjivesterby** [comment]
@030 Can you provide a code example of this not working on an existing issue?

**Comment by 030** [comment]
I used the `Issue.Update(&ji)` in conjunction with `jira.Issue{Key: "ticker-number"}. I did not save the code snippet and received the same error https://github.com/andygrunwald/go-jira/issues/191#issuecomment-531726884

**Comment by benjivesterby** [comment]
@030 can you please add a new issue. It looks to me like there is a typo. 

https://github.com/andygrunwald/go-jira/blob/master/issue.go#L117

It should be `Watchers` and the json should be `watchers` instead of `Watches` and `watches`

I'll see if that is actually the issue and PR it if it is when I have some time. You're welcome to make the update and PR it if you're willing. We always welcome contributions. 👍

**Comment by 030** [comment]
@benjivesterby new issue has been created

**Comment by cfloody** [comment]
Here's a quick workaround that worked for me:

First, figure out the custom field ID for the `Watchers` field
```
var customFieldID string
fieldList, _, _ := client.Field.GetList()

for _, v := range fieldList {
        if v.Name == "Watchers" {
                customFieldID = v.ID
                break
        }
}
```

Then set the values for that custom field in the `Unknowns` map

```
i := jira.Issue{
        Fields: &jira.IssueFields{
                Unknowns: map[string]interface{}{
                        customFieldID: []*jira.Watcher{
                                {
                                        Name: "cfloody",
                                },
                        },
                },
                Description: description,
                Type: jira.IssueType{
                        Name: "Task",
                },
                Project: jira.Project{
                        Key: "Foo",
                },
                
                Summary: summary,
                Priority: &jira.Priority{
                        Name: "Low",
                },
        },
}
```
