### ISSUE TITLE
panic seen when call UserService.GetSelf func with unauthorized user

### ISSUE THREAD

**Issue by jiaohe** [andygrunwald/go-jira#198]
runtime.goexit
	/tmp/build/38b8ed6e/gopath/src/git.calculi.com/calculi/projectmgmt-service/handler/jiraPoller.go:31
	git.calculi.com/calculi/projectmgmt-service/handler.PollPMServer
	/tmp/build/38b8ed6e/gopath/src/git.calculi.com/calculi/projectmgmt-service/handler/jiraPoller.go:54
	git.calculi.com/calculi/projectmgmt-service/handler.doPollAndUpdate
	/tmp/build/38b8ed6e/gopath/src/git.calculi.com/calculi/projectmgmt-service/handler/jiraPoller.go:87
	git.calculi.com/calculi/projectmgmt-service/handler.JiraPollAndUpdate
	/tmp/build/38b8ed6e/gopath/src/git.calculi.com/calculi/projectmgmt-service/handler/jira.go:339
	git.calculi.com/calculi/projectmgmt-service/handler.(*Jira).PollJira
	/tmp/build/38b8ed6e/gopath/src/git.calculi.com/calculi/projectmgmt-service/handler/jira.go:361
	git.calculi.com/calculi/projectmgmt-service/handler.(*Jira).CreateUpdateJql
	/tmp/build/38b8ed6e/gopath/src/git.calculi.com/calculi/projectmgmt-service/handler/jira.go:328
	git.calculi.com/calculi/projectmgmt-service/handler.(*Jira).GetJiraTimeZone
	/tmp/build/38b8ed6e/gopath/src/github.com/andygrunwald/go-jira/user.go:141
	github.com/andygrunwald/go-jira.(*UserService).GetSelf
	/tmp/build/38b8ed6e/gopath/src/github.com/andygrunwald/go-jira/error.go:41
	github.com/andygrunwald/go-jira.NewJiraError
	</html>
	</body>
	</div></div>
	</section>
	</div>
	<p><a href="/secure/MyJiraHome.jspa">Go to Jira home</a></p>
	<p>Basic Authentication Failure - Reason : AUTHENTICATED_FAILED</p>
	<p>Encountered a <code>&quot;401 - Unauthorized&quot;</code> error while loading this page.</p>
	<div class="aui-message aui-message-warning warning">
	</div></header>
	</div>
	<h1>Unauthorized (401)</h1>
	<div class="aui-page-header-main">
	<header class="aui-page-header"><div class="aui-page-header-inner">
	<section class="aui-page-panel-content">
	<div class="aui-page-panel"><div class="aui-page-panel-inner">
	<body id="jira" class="aui-layout aui-style-default page-type-message" data-version="7.12.3" >
	</head>
	<meta name="application-name" content="JIRA" data-name="jira" data-version="7.12.3">
	<script type="text/javascript" src="/rest/api/1.0/shortcuts/712004/d1dd9a316fcbbe6e17da4ed9d77b4cf7/shortcuts.js"></script>
	<link type="text/css" rel="stylesheet" href="/s/e09b8b0e4f4ea4e10f57dd6fc9a0fe03-CDN/lq6itl/712004/e8de97441587987122b2f74e3d450e41/8024a22e5e41f3539da669610f305c0a/_/download/contextbatch/css/jira.global.look-and-feel,-_super/batch.css?spectrum=true" data-wrm-key="jira.global.look-and-feel,-_super" data-wrm-batch-type="context" media="all">
	<script type="text/javascript" src="/s/66c4480c17f4d4ecdbbebf89e86c236f-CDN/lq6itl/712004/e8de97441587987122b2f74e3d450e41/92d1a3130d723910ffc07a04c3703e9c/_/download/contextbatch/js/jira.global,-_super/batch.js?locale=en&amp;spectrum=true" data-wrm-key="jira.global,-_super" data-wrm-batch-type="context" data-initially-rendered></script>
	<script type="text/javascript" src="/s/e80a0b95ba25edea1d1bb8c705c75cbb-CDN/lq6itl/712004/e8de97441587987122b2f74e3d450e41/9296915968fd19e3630cf5546b9a3e64/_/download/contextbatch/js/atl.global,-_super/batch.js?locale=en&amp;spectrum=true" data-wrm-key="atl.global,-_super" data-wrm-batch-type="context" data-initially-rendered></script>
	<script type="text/javascript" src="/s/3d680610577c99c91ad7451249ccb1ce-CDN/lq6itl/712004/e8de97441587987122b2f74e3d450e41/dbc5f817b9a3a6f6dd84bc8f7d6397f5/_/download/contextbatch/js/jira.general,-_super/batch.js?locale=en&amp;spectrum=true" data-wrm-key="jira.general,-_super" data-wrm-batch-type="context" data-initially-rendered></script>
	<script type="text/javascript" src="/s/c643e63e015b13abed2e416e94f3ea8a-CDN/lq6itl/712004/e8de97441587987122b2f74e3d450e41/f0bc191e154e9fcc2351fb12c1eb340f/_/download/contextbatch/js/atl.general,-_super/batch.js?agile_global_admin_condition=true&amp;is-server-instance=true&amp;jag=true&amp;locale=en&amp;nps-acknowledged=true&amp;spectrum=true&amp;whisper-enabled=true" data-wrm-key="atl.general,-_super" data-wrm-batch-type="context" data-initially-rendered></script>
	<script type="text/javascript" src="/s/e22e0f73af937c83c6e4b0a98a6b5090-CDN/lq6itl/712004/e8de97441587987122b2f74e3d450e41/2b7752380480579feee3c2e40dde2925/_/download/contextbatch/js/_super/batch.js?locale=en&amp;spectrum=true" data-wrm-key="_super" data-wrm-batch-type="context" data-initially-rendered></script>
	<link type="text/css" rel="stylesheet" href="/s/0f2913dc3d5c1ceef7bfc64713211f10-CDN/lq6itl/712004/e8de97441587987122b2f74e3d450e41/1.0/_/download/batch/jira.webresources:global-static/jira.webresources:global-static.css" data-wrm-key="jira.webresources:global-static" data-wrm-batch-type="resource" media="all">
	<link type="text/css" rel="stylesheet" href="/s/550aba50da66158dd0c4c8aebaddd283-CDN/lq6itl/712004/e8de97441587987122b2f74e3d450e41/1.0/_/download/batch/jira.webresources:global-static-adgs/jira.webresources:global-static-adgs.css?spectrum=true" data-wrm-key="jira.webresources:global-static-adgs" data-wrm-batch-type="resource" media="all">
	<link type="text/css" rel="stylesheet" href="/s/dbfa9160361595bf23a5d6c563868203-CDN/lq6itl/712004/e8de97441587987122b2f74e3d450e41/7.9.9/_/download/batch/com.atlassian.auiplugin:aui-labels/com.atlassian.auiplugin:aui-labels.css" data-wrm-key="com.atlassian.auiplugin:aui-labels" data-wrm-batch-type="resource" media="all">
	<link type="text/css" rel="stylesheet" href="/s/501b0285b21239ec2215fa11bc393c08-CDN/lq6itl/712004/e8de97441587987122b2f74e3d450e41/92d1a3130d723910ffc07a04c3703e9c/_/download/contextbatch/css/jira.global,-_super/batch.css?spectrum=true" data-wrm-key="jira.global,-_super" data-wrm-batch-type="context" media="all">
	<link type="text/css" rel="stylesheet" href="/s/70e2b24f7d348efe6b30b41469d5070c-CDN/lq6itl/712004/e8de97441587987122b2f74e3d450e41/dbc5f817b9a3a6f6dd84bc8f7d6397f5/_/download/contextbatch/css/jira.general,-_super/batch.css?spectrum=true" data-wrm-key="jira.general,-_super" data-wrm-batch-type="context" media="all">
	<link type="text/css" rel="stylesheet" href="/s/ec1ad3d96e769c49f73cfdc3b34707d1-CDN/lq6itl/712004/e8de97441587987122b2f74e3d450e41/f0bc191e154e9fcc2351fb12c1eb340f/_/download/contextbatch/css/atl.general,-_super/batch.css?agile_global_admin_condition=true&amp;is-server-instance=true&amp;jag=true&amp;nps-acknowledged=true&amp;spectrum=true&amp;whisper-enabled=true" data-wrm-key="atl.general,-_super" data-wrm-batch-type="context" media="all">
	<link type="text/css" rel="stylesheet" href="/s/eeebf4a7c8b75eac14a2fe14d259c7d7-CDN/lq6itl/712004/e8de97441587987122b2f74e3d450e41/2b7752380480579feee3c2e40dde2925/_/download/contextbatch/css/_super/batch.css?spectrum=true" data-wrm-key="_super" data-wrm-batch-type="context" media="all">
	if(window.WRM._dataArrived)window.WRM._dataArrived();</script>
	WRM._unparsedData["com.atlassian.plugins.helptips.jira-help-tips:help-tip-manager.JiraHelpTipData"]="{\"anonymous\":true}";
	WRM._unparsedData["jira.webresources:user-message-flags.adminLockout"]="{}";
	WRM._unparsedData["com.atlassian.jira.plugins.jira-wiki-editor:wiki-editor-resources.help-data"]="{\"showHelp\":true,\"editorDocumentationUrl\":[\"https://docs.atlassian.com/jira/jcore-docs-0712/Visual+editing\"],\"editorDocumentationTitle\":[\"Show me documentation for the visual editor\"]}";
	WRM._unparsedData["com.atlassian.jira.plugins.jira-wiki-editor:wiki-editor-thumbnails.thumbnails-allowed"]="true";
	WRM._unparsedData["com.atlassian.whisper.atlassian-whisper-plugin:atlassian-whisper-bootstrap.WhisperData"]="{\"hasMessages\":false,\"syncInit\":false,\"baseUrl\":\"https:\\/\\/jira.calculi.com\"}";
	WRM._unparsedData["com.atlassian.jira.project-templates-plugin:project-templates-plugin-resources.ptAnalyticsData"]="{\"instanceCreatedDate\":\"2016-10-17\"}";
	WRM._unparsedData["com.atlassian.jira.jira-header-plugin:newsletter-signup-tip-init.newsletterSignup"]="{\"signupDescription\":\"Get updates, inspiration and best practices from the team behind Jira.\",\"formUrl\":\"https://www.atlassian.com/apis/exact-target/{0}/subscribe?mailingListId=1401671\",\"signupTitle\":\"Sign up!\",\"signupId\":\"newsletter-signup-tip\",\"showNewsletterTip\":false}";
	WRM._unparsedData["com.atlassian.jira.jira-header-plugin:dismissedFlags.flags"]="{\"dismissed\":[]}";
	WRM._unparsedData["jira.webresources:avatar-picker.data"]="{}";
	WRM._unparsedData["jira.webresources:dateFormatProvider.allFormats"]="{\"dateFormats\":{\"meridiem\":[\"AM\",\"PM\"],\"eras\":[\"BC\",\"AD\"],\"months\":[\"January\",\"February\",\"March\",\"April\",\"May\",\"June\",\"July\",\"August\",\"September\",\"October\",\"November\",\"December\"],\"monthsShort\":[\"Jan\",\"Feb\",\"Mar\",\"Apr\",\"May\",\"Jun\",\"Jul\",\"Aug\",\"Sep\",\"Oct\",\"Nov\",\"Dec\"],\"weekdaysShort\":[\"Sun\",\"Mon\",\"Tue\",\"Wed\",\"Thu\",\"Fri\",\"Sat\"],\"weekdays\":[\"Sunday\",\"Monday\",\"Tuesday\",\"Wednesday\",\"Thursday\",\"Friday\",\"Saturday\"]},\"lookAndFeelFormats\":{\"relativize\":\"true\",\"time\":\"h:mm a\",\"day\":\"EEEE h:mm a\",\"dmy\":\"dd/MMM/yy\",\"complete\":\"dd/MMM/yy h:mm a\"}}";
	WRM._unparsedData["com.atlassian.analytics.analytics-client:programmatic-analytics-init.programmatic-analytics-data-provider"]="false";
	WRM._unparsedData["com.atlassian.analytics.analytics-client:policy-update-init.policy-update-data-provider"]="false";
	WRM._unparsedData["jira.webresources:default-comment-security-level.DefaultCommentSecurityLevelHelpLink"]="{\"extraClasses\":\"default-comment-level-help\",\"title\":\"Commenting on an Issue\",\"url\":\"https://docs.atlassian.com/jira/jcore-docs-0712/Editing+and+collaborating+on+issues#Editingandcollaboratingonissues-restrictacomment\",\"isLocal\":false}";
	WRM._unparsedData["jira.webresources:feature-flags.feature-flag-data"]="{\"enabled-feature-keys\":[\"com.atlassian.jira.agile.darkfeature.editable.detailsview\",\"nps.survey.inline.dialog\",\"com.atlassian.jira.agile.darkfeature.edit.closed.sprint.enabled\",\"jira.plugin.devstatus.phasetwo\",\"jira.frother.reporter.field\",\"atlassian.rest.xsrf.legacy.enabled\",\"jira.issue.status.lozenge\",\"com.atlassian.jira.config.BIG_PIPE\",\"com.atlassian.jira.projects.issuenavigator\",\"com.atlassian.jira.config.PDL\",\"jira.plugin.devstatus.phasetwo.enabled\",\"atlassian.aui.raphael.disabled\",\"app-switcher.new\",\"frother.assignee.field\",\"com.atlassian.jira.projects.ProjectCentricNavigation.Switch\",\"jira.onboarding.cyoa\",\"com.atlassian.jira.agile.darkfeature.kanplan.enabled\",\"com.atlassian.jira.config.ProjectConfig.MENU\",\"com.atlassian.jira.projects.sidebar.DEFER_RESOURCES\",\"com.atlassian.jira.agile.darkfeature.kanplan.epics.and.versions.enabled\",\"com.atlassian.jira.agile.darkfe
	WRM._unparsedData["com.atlassian.plugins.atlassian-plugins-webresource-plugin:context-path.context-path"]="\"\"";
	window.WRM=window.WRM||{};window.WRM._unparsedData=window.WRM._unparsedData||{};window.WRM._unparsedErrors=window.WRM._unparsedErrors||{};
	<script>
	</script>
	})();
	});
	}
	contextPath = value;
	sendDeprecatedEvent('set');
	printDeprecatedMsg();
	set: function(value) {
	},
	return contextPath;
	sendDeprecatedEvent('get');
	printDeprecatedMsg();
	get: function() {
	Object.defineProperty(window, 'contextPath', {
	}
	}
	setTimeout(sendDeprecatedEvent, 1000);
	eventBuffer.push(postfix);
	} catch(ex) {

	}
	sendEvent(analytics, postfix);
	if (postfix) {
	}
	eventBuffer = [];
	});
	sendEvent(analytics, value);
	eventBuffer.forEach(function(value) {
	if (eventBuffer.length) {
	var analytics = require('jira/analytics');
	try {
	function sendDeprecatedEvent(postfix) {
	}
	});
	name: 'js.globals.contextPath.' + postfix
	analytics.send({
	function sendEvent(analytics, postfix) {
	}
	}
	console.warn('DEPRECATED JS - contextPath global variable has been deprecated since 7.4.0. Use `wrm/context-path` module instead.');
	if (console && console.warn) {
	function printDeprecatedMsg() {
	var eventBuffer = [];
	var contextPath = '';
	(function() {
	<script type="text/javascript">
	
	<title>Unauthorized (401)</title>
	<head>
	<html>
	401 Unauthorized:

**Comment by andygrunwald** [comment]
Fixed in https://github.com/andygrunwald/go-jira/pull/199
