### ISSUE TITLE
Searching for issues and expanding fields

### ISSUE THREAD

**Issue by rikonor** [andygrunwald/go-jira#202]
Hi,

I'm trying to search for issues and expand issue comments, but am having some trouble.

Here's an example of what I'm doing:
```go
// fetches issues successfully based on query but does not expand anything
iss, _, err := jiraClient.Issue.Search(q, nil)

// for some reason this returns nothing
iss, _, err := jiraClient.Issue.Search(q, &jira.SearchOptions{})

// also finds nothing, not sure how to expand the comments
iss, _, err := jiraClient.Issue.Search(q, &jira.SearchOptions{
	Expand: "comments",
})
```

I can repeat fetching an issue with `Get` to get the comments, but I figure that's a really inefficient way to do it.

Any chance you might have some idea how to do this properly?

Thank you!

**Comment by ghostsquad** [comment]
@rikonor did you solve your own problem? If so, can you document that here in case someone else runs into a similar issue?

**Comment by rikonor** [comment]
@ghostsquad  Sorry, I figured it out a few minutes after posting this. It was just a matter of including a `MaxResults` in the options. I think it might be nicer if in [Search](https://github.com/andygrunwald/go-jira/blob/master/issue.go#L826), it would build the query params based on which options were set, e.g if `MaxResults` is 0, not include that query params in the URL, etc, which would be equivalent to providing a nil options argument.

**Comment by ghostsquad** [comment]
@rikonor that's the problem with using structs as options. Zero values have meaning. Here's more information about this problem: https://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis

I'll keep this in mind for changes in V2
