### ISSUE TITLE
IssueLinks unsupported in create function

### ISSUE THREAD

**Issue by i-wilson** [andygrunwald/go-jira#210]
{"errorMessages":[],"errors":{"issuelinks":"Field does not support update 'issuelinks'"}}

I get the above error when attempting to create an issue with a link, and according to (this)[https://community.atlassian.com/t5/Answers-Developer-Questions/rest-api-link-issue-while-creating-issue/qaq-p/480766] forum post I don't believe it's supported in jira's api. Should this be removed from go-jira?

**Comment by ghostsquad** [comment]
The way the code is setup, is that the same object is used for creation as well as what's returned when getting or finalizing after create. As such, you would see a similar error if you try to set the ID on the object when trying to create it. Hopefully that makes sense?

**Comment by ghostsquad** [comment]
If the response above does not answer your question, please feel free to reopen this issue or file a new one. Thanks!
