### ISSUE TITLE
board type list option incombatible with REST API

### ISSUE THREAD

**Issue by xaniasd** [andygrunwald/go-jira#213]
according to the [docs](https://docs.atlassian.com/jira-software/REST/7.0.4/#agile/1.0/board-getAllBoards) BoardListOptions.BoardType should be mapped to type, now it's boardType.

Because of this, filtering boards based on type does not work.

Shall I create a PR?

**Comment by ghostsquad** [comment]
PR's always welcome! When creating your PR the minimum expectations are:

* Backwards Compatibility is maintained
* Tests - Both positive and negative
* Commit Message - Follows this standard: https://chris.beams.io/posts/git-commit/
