### ISSUE TITLE
Mentioning in the Golang Weekly Newsletter

### ISSUE THREAD

**Issue by andygrunwald** [andygrunwald/go-jira#217]
Hey folks,

this morning I found out that this project has been mentioned in the Golang Weekly Newsletter. See https://golangweekly.com/issues/263

This keeps us motivated. Thanks a lot to all of you who contributed to this project by code, by helping in issues, by filling issues, by spreading the word or by helping colleagues using this library.

Thank you for making this possible!

@bidesh @spmassot  @zenixls2 @Thiht @rbriski @jasonobroin @Xjs @attack7 @nebril @b4b4r07 @shdunning @fkrauthan-hyperwallet @ghostsquad @is2ei @omira-sch @guywithnose @dougEfresh @Rambatino @urld @writemem @solcates @chilicheech @oroshnivskyy @vovka667 @jdevelop @shawncatz @nguyen970 @blachniet @juicemia @antifuchs @ggrpmnn @gphakos @phille97 @kennylevinsen @avadhutp @rumyantseva @edwinakatosh @falnyr @xaniasd @benmcginnis @lzakharov @davidnewman @vsellier @corybwhite @dvdizon @ahammond @machiel @Tom-Xie @natemara @sleeper

**Comment by andygrunwald** [comment]
Hey all,
check this issue out! This is for you!

@BattleBas @ishugupta92 @Hoid @robiball @davidkuridza @ikornienko @manute @francoishill @yanolab @wvell @AlbinOS @pmoncadaisla @dontrebootme @guilhermebr @bah2830 @antekresic @ifosch @dimfeld

**Comment by ghostsquad** [comment]
Good times! Keep up the quality PRs!
