### ISSUE TITLE
Convert Jira (Atlassian WikiMarkUp) to Github Markdown?

### ISSUE THREAD

**Issue by StevenACoffman** [andygrunwald/go-jira#227]
So I'm just checking to see if you would be interested in a contribution. I wrote in pure golang a conversion from Jira's Markup to Github Markdown. It is not a formal Parsing Expression Grammar, but it does a pretty good job. It turns out that I can actually do the reverse pretty well too (github markdown to jira), not that I actually need that capability.

Would that be a useful capability for this project, or too out of scope? No worries either way. Thanks for making cool stuff.

**Comment by andygrunwald** [comment]
Thanks for your request @StevenACoffman.
I think it is out of the scope of this library. If your transformer is using go-jira under the hood, I would be happy to include your repo in the readme as a potential use-case.

**Comment by StevenACoffman** [comment]
Thanks, I spun it into a library for others here: https://github.com/StevenACoffman/j2m

As such it has no dependencies on go-jira, but it can be easily added to go-jira. For instance, I automate making github pull requests populated with jira's issue description in the pull request description. Thanks again for making cool stuff!

**Comment by andygrunwald** [comment]
Good work, Steven!
Thanks for letting us know.
