### ISSUE TITLE
Comments are not unmarshalled

### ISSUE THREAD

**Issue by ifosch** [andygrunwald/go-jira#23]
Using go-jira for a CLI, I found that comments are not being unmarshalled for any Issue.
I did the following try on your code, and got `issue_test` doesn't pass. In https://github.com/andygrunwald/go-jira/blob/master/issue_test.go#L140, I added:
```go
if len(issue.Fields.Comments) != 1 {
  t.Error("Expected one comment, %v found", len(issue.Fields.Comments))
}
```
I'm not very experienced in Go programming and even most not sure of understanding JSON Unmarshalling anyway, so I might be wrong. I might like to contribute a fix for this, but I'm uncertain about this actually being a bug, or how to diagnose and fix... I also found another issue, trying to see the response body, but this should probably be another issue.

I apologize if this is not the correct way to contribute, or help; I'm just trying to use this :)

**Comment by andygrunwald** [comment]
Thanks. Was fixed in #24
