### ISSUE TITLE
Help with Issue.UpdateIssue function

### ISSUE THREAD

**Issue by SeanTurner026** [andygrunwald/go-jira#236]
Hi,

Bear with me please as this is my first golang project. I have plans to make this more syntactically go in the future, but for now I'm just trying to get something that works and go from there.

I'm trying to write a simple cli application that takes the number in a jira ticket as a flag, and updates the associated ticket as `Done`.

I'm running into an issue with my `payload` specifically with `Resolution: "Done",`. The issue is `cannot use "Done" (type string) as type *jira.Resolution in field value`

Here's my code. Any help would be greatly appreciated, and I would be happy to contribute to the `examples` when I'm up and running :)

```
package main

import (
	"flag"
	"fmt"
	"os"
	"strconv"

	jira "github.com/andygrunwald/go-jira"
)

func main() {

	key := flag.Int("key", 0, "jira integer key to interact with")

	flag.Parse()

	if *key == 0 {
		fmt.Println("Please specify a jira ticket integer with --key")
		os.Exit(1)
	}

	tp := jira.BasicAuthTransport{
		Username: "un",
		Password: "pw",
	}

	client, err := jira.NewClient(tp.Client(), "https://org.atlassian.net")
	if err != nil {
		fmt.Printf("\nerror: %v\n", err)
	}

	ticket := "jiraProject-" + strconv.Itoa(*key)

	payload := jira.CreateTransitionPayload{
		Fields: jira.TransitionPayloadFields{
			Resolution: "Done",
		},
	}

	resp, err := client.Issue.UpdateIssue(ticket, payload)
	if err != nil {
		fmt.Println(err)
	}
}
```

**Comment by ghostsquad** [comment]
Right, so the error says it all. `Resolution` field is not a string. It's a `*jira.Resolution` type. Here's the type that you need to use.

https://github.com/andygrunwald/go-jira/blob/37f2d5b7594981def803aab0a8f21516afa13f92/resolution.go

Also note, that it's a pointer, so the code might look something like this:

```go
Fields: jira.TransitionPayloadFields{
	Resolution: &jira.Resolution{
		....
	},
},
```

Assuming that the resolutions don't change often, it's probably safe to get a list of resolutions once, and hard code the information.

```go
fmt.Printf("%#v", client.Resolution.GetList())
```

or

```go
import "github.com/davecgh/go-spew/spew"

spew.Dump(client.Resolution.GetList())
```

**Comment by SeanTurner026** [comment]
Thank you very much for the feedback, it was helpful.

Inside of my `main()`, I now have the following:

```
	payload := jira.CreateTransitionPayload{
		Fields: jira.TransitionPayloadFields{
			Resolution: &jira.Resolution{
				ID: "10000",
			},
		},
	}

	_, err = client.Issue.DoTransitionWithPayload(ticket, payload)
	if err != nil {
		fmt.Println(err)
	}
```

And I'm getting an error which states `'transition' identifier must be an integer: Request failed. Please analyze the request body for more details. Status code: 400`.

I know I'm still doing something wrong because the ID is supposed to be a string while the error is calling for an integer. 

https://github.com/andygrunwald/go-jira/blob/37f2d5b7594981def803aab0a8f21516afa13f92/resolution.go#L14

I've also tried passing in the proper values for status `Done` that were returned by `client.Resolution.GetList()`, but I still received the same error.

Am I using the wrong function?

**Comment by ghostsquad** [comment]
notice how the transition payload struct has multiple fields:
https://github.com/andygrunwald/go-jira/blob/master/issue.go#L313

type CreateTransitionPayload struct {
	Transition TransitionPayload       `json:"transition" structs:"transition"`
	Fields     TransitionPayloadFields `json:"fields" structs:"fields"`
}

You aren't providing the `Transition` object. 

https://github.com/andygrunwald/go-jira/blob/master/issue.go#L300

**Comment by SeanTurner026** [comment]
Thank you very very for the help. I was able to sort myself out using the below:

If this transition number `31` isn't consistent across tickets I'll be back to the drawing board.

```
        // get a list of possible transitions
	// fmt.Println(client.Issue.GetTransitions(ticket))
	resp, err := client.Issue.DoTransition(ticket, "31")
	if err != nil {
		fmt.Println(err)
	}
```

One last question, would it be helpful if `DoTransition()` had different logic where it checks to see what available statuses are (e.g. `TO DO`, `DONE`), and in turn takes a status string as an input instead of a number?

**Comment by ghostsquad** [comment]
The reason it takes a number instead of a status is because of how the Jira API and underlying system works. It's not a declarative system, such as ” please make this ticket DONE, by whatever means”, it's more like, "please execute this transition" which will put it in done.

Note that JIRA workflows are very powerful, and it may be the case that not all statuses are available from any given state, and to close a ticket may actually require several transitions.

The default workflows are pretty simple though.

Unfortunately, what this means is that as a developer, you may have to get very specific, and hardcore specific things depending on the project, issue type, etc, and coordinate with The JIRA admin to ensure your tool doesn't break from workflow changes.
