### ISSUE TITLE
How to get comments on an issue?

### ISSUE THREAD

**Issue by peterecho** [andygrunwald/go-jira#237]
I see that there are structs for Comments and Comment, but how do I actually get the list of comments from an issue?

**Comment by ghostsquad** [comment]
does `myissue.Comments` not work? https://github.com/andygrunwald/go-jira/blob/master/issue.go#L130

**Comment by peterecho** [comment]
I think it's `myissue.Fields.Comments` and I don't believe so. I tried this:

```
if issue.Fields.Comments != nil {
		for _, comment := range issue.Fields.Comments.Comments {
			fmt.Println(comment.Body)
		}
	}
```

but issue.Fields.Comments just returns nil, even for issues that have comments.

**Comment by ghostsquad** [comment]
Have you tried `issue.Comments`?

**Comment by peterecho** [comment]
yeah and here is the result: `.\main.go:314:19: issue.Comments undefined (type jira.Issue has no field or method Comments)`

**Comment by ghostsquad** [comment]
oh I apologize. I misread. Let me look into this more.

**Comment by ghostsquad** [comment]
according to the documentation, if you get a _specific_ JIRA issue, you should get back comments. This is not the case if you are getting a list of issues (say from a search).

https://docs.atlassian.com/software/jira/docs/api/REST/8.2.6/#api/2/issue-getIssue

How are you getting your issue? I was able to get comments with this code here:

```go
package main

import (
    "fmt"
    "github.com/andygrunwald/go-jira"
)

func main() {
	jiraClient, _ := jira.NewClient(nil, "https://issues.apache.org/jira/")
	issue, _, _ := jiraClient.Issue.Get("MESOS-3325", nil)
	if issue.Fields.Comments != nil {
		fmt.Printf("%d\n", len(issue.Fields.Comments.Comments))

		for _, comment := range issue.Fields.Comments.Comments {
			fmt.Println(comment.Body)
		}
	} else {
		fmt.Println("Comments is nil")
	}
}


```

```
$ go run main.go
2
Hi, We hit this issue months ago, mesos agent always read boot_id from host os and re-generate the slave id and register with master, I remember here is a issue to track this, but I forget the issue id, you can give a boot id to the agent to make sure the slave id do not change when restart.
Closing this issue because:
* Version 0.23 is no longer supported (more than 1 year old).
* Running the agent in a container has many known issues that may have already been fixed later.

```

**Comment by peterecho** [comment]
Ahhh... I was getting a list of issues, the code you show works for me as well. Thanks!
