### ISSUE TITLE
BasicAuthTransport - lack of information hiding

### ISSUE THREAD

**Issue by perolausson** [andygrunwald/go-jira#241]
Hi Andy, I noticed a difference in how the authentication has been handled between the go-gerrit and go-jira. 

In the former, you only provide a struct with non-exported fields and only provide setters, but in the latter you use a struct with exported fields and no setters and obviously it is very open.

It would be nice if you could refactor go-jira to have the same solution as go-gerrit because in the use case I am thinking of, the users who would be utilising go-jira should not be able to find out what the tokens are which are used to authenticate with Jira. 

Does that make sense or are there other ways of exposing the tokens anyhow which renders the exercise of hiding this futile?

**Comment by andygrunwald** [comment]
It sounds reasonable. Without having a look at the code yet, I assume this change would be a breaking change.
Considering this, the question of the value will appear. Is there any potential/practical risk here? E.g. leaking information?
A breaking change might disappoint users (yes, we can raise the major version number to indicate this).

That both libs (go-gerrit / go-jira) has different ways of handling this, which can be true. I don't know the reason, but I assume that both were written at different times (and with different knowledge) or the feature/code was contributed or reworked by the community. Or maybe I wanted to try out different things. In general, I can't remember.

Anyhow: Thanks for the thoughts! (and it is beautiful to read that you had a look at both libs).
@rbriski / @ghostsquad Whats your opinion here?

**Comment by ghostsquad** [comment]
General immutably, and write only secrets does seem like a good practice.
Though, I'm not entirely sure this is actually a security issue, since your
trust boundary should include your code and all the dependencies in your
app.

Cheers,
Wes

**Comment by ghostsquad** [comment]
@perolausson I'm going to close this issue, as it's stale. I'll keep this in mind for v2 enhancements though.
