### ISSUE TITLE
[BUG] AddWorklogRecord - error 400 Unrecognized field "locale"

### ISSUE THREAD

**Issue by prugala** [andygrunwald/go-jira#242]
Hello

I have a problem with using `AddWorklogRecord` method. All the time I get response 400:

> error: Unrecognized field "locale" (Class com.atlassian.jira.issue.fields.rest.json.beans.UserJsonBean), not marked as ignorable
>  at [Source: org.apache.catalina.connector.CoyoteInputStream@618efea; line: 1, column: 1090] (through reference chain: com.atlassian.jira.issue.fields.rest.json.beans.WorklogJsonBean["author"]->com.atlassian.jira.issue.fields.rest.json.beans.UserJsonBean["locale"]): Request failed. Please analyze the request body for more details. Status code: 400

Example code:
```
        user, _, _ := c.User.GetSelf()
	timeSpentSeconds := int(timeSpent)

	worklogRecord := jira.WorklogRecord{
		Author:           user,
		Comment:          description,
		Started:          &startTime,
		TimeSpentSeconds: timeSpentSeconds,
		IssueID:          issueId,
	}

	worklog, _, err := c.Issue.AddWorklogRecord(issueId, &worklogRecord)
```

User struct has field `Locale`  and I think Jira API endpoint dosent expect this field for user.

**Jira: SAAS - hosted by Atlassian**

**Comment by ghostsquad** [comment]
@prugala can you describe why you closed this issue in case someone else stumbles across it with a similar problem?

**Comment by prugala** [comment]
@ghostsquad ye, my bad that I closed issue without response.

It was my bad, I created worklog with too much data example `Author, IssueID`. I should add only:
`Comment`, `Started`, `TimeSpentSeconds` / `TimeSpent`
