### ISSUE TITLE
Unable to add comment during transition

### ISSUE THREAD

**Issue by ghostsquad** [andygrunwald/go-jira#248]
On behalf of @hdshah-dev

> Hello Andy,
I am using go-jira client version 1.11.1. I am trying to see an option to change the transition of an issue with a comment (as part of the update). I do see DoTransitionWithPayload() method to allow a payload TransitionPayload (struct). However I dont see a way to set the comment in TransitionPayload struct or there is one to be used. Can you please confirm if this feature is yet to be implemented or if otherwise can you provide an example to do?
Thanks

**Comment by ghostsquad** [comment]
According to this:
https://docs.atlassian.com/software/jira/docs/api/REST/6.2.5/#d2e1171

> The fields that can be set on transtion, in either the fields parameter or the update parameter can be determined using the /rest/api/2/issue/{issueIdOrKey}/transitions?expand=transitions.fields resource. If a field is not configured to appear on the transition screen, then it will not be in the transition metadata, and a field validation error will occur if it is submitted.

This leaves me to believe that we probably shouldn't be used `TransitionFields` here:
https://github.com/andygrunwald/go-jira/blob/1946cac0fe6ee91f784e3dda3c12f3f30f7115b8/issue.go#L325

We should use `IssueFields`, as this would provide the greatest flexibility.

Howevever, This is a backwards incompatible change.

There's good news though!

```
func (s *IssueService) DoTransitionWithPayload(ticketID, payload interface{}) (*Response, error) {
```

`payload` here is an `interface{}` can you pass an arbitrary struct to it, which means you can make your own `TransitionPayload` with the right tags to be serialized properly.

Finally some more bad news:

Your mileage may very. I found an open Atlassian issue about this exact thing, and it appears to not be well supported.

https://jira.atlassian.com/browse/JSDSERVER-5034

**Comment by hdshah-dev** [comment]
Hello,
Thank you for prompt reply on this and detailed info. I tried with my custom structure as below
```
payload := CreateTransitionPayload{
		Transition: TransitionPayload{
			ID: transitionID,
		},
		Update: TransitionPayloadFields{
			Comment: []Comment{{Add: AddComment{Body: "Fixed...again"}}},
		},
	}
```
However the _Update_ field gets changed to _Fields_ as  somewhere down the json encoder code path as below
```
{
  "transition": {
    "id": "101"
  },
  "**fields**": {
    "Comment": [
      {
        "Add": {
          "Body": "Fixed...again"
        }
      }
    ]
  }
}
```
Using cURL command I was able to transition the state with a comment that needs to be filled in the popup screen by having the payload below
{
	"transition": {
    		"id": "101"
	},
	 "**update**": {
        "comment": [
            {
                "add": {
                    "body": "Bug has been fixed."
                }
            }
        ]
    }
}
Any advice if there is a way to not have **Update** field change to **Fields** or any other work around?
Thanks

**Comment by ghostsquad** [comment]
Can you provide the struct definition you are using?

**Comment by hdshah-dev** [comment]
Nevermind, I was using the wrong tag for the struct. After changing it as below I was able to `DoTransitionWithPayload()` with a comment to add...Hallelujah!

```
type TransitionPayloadFields struct {
	Comment []Comment `json:"comment" structs:"comment"`
}
```

**Comment by ghostsquad** [comment]
Woo!

If you want to add this field to the existing TransitionPayload struct, we are accepting PRs! It would help others who may be running into the same problem.

For now though, I'll close this issue.
