### ISSUE TITLE
PostAttachment auth issue

### ISSUE THREAD

**Issue by antekresic** [andygrunwald/go-jira#25]
Hi.

Looks like there is some sort of issue with PostAttachment method. I'm getting 401 HTTP error code from the Jira service when trying to use it. Here is my example code:

https://gist.github.com/antekresic/4dda591c415d4a9dac5179efd1f7fd96
(I removed the credentials and other sensitive data)

By modifying jira.go file, the NewMultiPartRequest method on the Client, I was able to get it working. I changed the session cookie setting to be just like in the NewRequest method.

Let me know if you need more info regarding this issue.

Thanks!

**Comment by jasonob** [comment]
Can you show what change you made to NewMultiPartRequest?

You added this?

// Set session cookie if there is one
	if c.session != nil {
		for _, cookie := range c.session.Cookies {
			req.AddCookie(cookie)
		}
}

Did you leave in this ?

// Set session cookie if there is one
	if c.Authentication.Authenticated() {
		req.Header.Set("Cookie", fmt.Sprintf("%s=%s", c.session.Session.Name, c.session.Session.Value))
	}


Cheers!

Jason

**Comment by antekresic** [comment]
Exactly that, I didn't leave the part you specified here, just replaced
with the first part.

Thanks.

**Comment by jasonob** [comment]
Looks good to me

Can you submit a pull request to Andy?

Thanks!

Jason

**Comment by andygrunwald** [comment]
Thank you @jasonob and @antekresic.
This make me smile and this is open source for me!
I love it when someone push something, other people start using it and once an issue occured the community helps each other. This is just great.
Thank you for this. You made my day.
