### ISSUE TITLE
support jira v3  apis

### ISSUE THREAD

**Issue by jomach** [andygrunwald/go-jira#250]
I'm getting 
```
level=debug ts=2020-01-31T11:24:06.97204685Z caller=notify.go:229 msg=handleJiraError api=Issue.Search err="The value 'PROM' does not exist for the field 'project'.: Request failed. Please analyze the request body for more details. Status code: 400" url="https://onetest123.atlassian.net/rest/api/2/search?jql=project%3D%22PROM%22+and+labels%3DalertingTest+order+by+resolutiondate+desc&maxResults=2&fields=summary,status,resolution,resolutiondate,project"
```

I think this is because this lib is not using v3 of the apis... Can someone check ? I'm trying to use jira service desk

Original issue: https://github.com/free/jiralert/issues/51

**Comment by ghostsquad** [comment]
Please provide the minimal code to reproduce this issue.

**Comment by jomach** [comment]
Ok, after some more looking it was wrong credentials. Maybe it would be great if the client could expose a method validate login instead of throwing this error.  A quick google search give us: https://community.atlassian.com/t5/Jira-Software-questions/REST-error-quot-The-value-XXX-does-not-exist-for-the-field/qaq-p/654730
