### ISSUE TITLE
UserKey and Usernames no longer accepted in JIRA API

### ISSUE THREAD

**Issue by dhollinger** [andygrunwald/go-jira#255]
The API now only accepts the `accountId` parameter on API endpoints that previous accepted Usernames or UserKeys.

https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/

**Comment by ghostsquad** [comment]
@dhollinger why was this immediately closed?

**Comment by TheKevJames** [comment]
Potentially a mistake to immediately close this?

I'm noticing that as of a couple days ago all my `assignee` values seem to be set to null, which I would assume might be related (I was just about to open an issue when I came across this) eg:
```
~ » jira view FOO-123
issue: FOO-123
created: 25 minutes ago
status: In Progress
summary: [redacted]
project: FOO
issuetype: Sub-task
assignee: <no value>
reporter: <no value>
priority: Medium
votes: 0
description: |
```

**Comment by ghostsquad** [comment]
@thekevjames are you reporting in the right repo? It looks like you might be looking for the go-jira/jira CLI which is not this project.

https://github.com/go-jira/jira

**Comment by TheKevJames** [comment]
/facepalm Yes, yes I am. Interestingly, that project has a [recently opened PR for fixing the problem I described](https://github.com/go-jira/jira/pull/315) already so... yeah, I'll just show myself out.

Sorry for any confusion!

**Comment by ghostsquad** [comment]
No worries! Thanks for stopping by. :beers:

**Comment by RKTMN** [comment]
UserKey and Usernames no longer accepted by the JIRA API is still a problem for this project; is there any movement towards fixing the issue for this project? Certain functionality (creation of issues, etc) will continue to be broken in the meantime as I understand it

**Comment by dhollinger** [comment]
@ghostsquad wrong repo. I wasn't paying attention and opened the issue here instead of at the go-jira/jira CLI tool repo-

**Comment by ghostsquad** [comment]
@RKTMN #259 addresses this
