### ISSUE TITLE
IssueService.GetWatchers does not work

### ISSUE THREAD

**Issue by clementlecorre** [andygrunwald/go-jira#256]
Hello!

I have a problem with `GetWatchers`(https://godoc.org/github.com/andygrunwald/go-jira#IssueService.GetWatchers) method.

For some time now, I've been getting 404 errors. After analyzing the code and the problem I think that the key 'name' does not exist anymore in the Jira return payload.

My error message :
```
Status code: 404: Could not parse JSON: unexpected end of JSON input 
```

API query (with curl) : `/rest/api/2/issue/ISSUE-KEY/watchers`
```json
{
  "self": "https://mydomain.atlassian.net/rest/api/2/issue/ISSUE-KEY/watchers",
  "isWatching": false,
  "watchCount": 1,
  "watchers": [
    {
      "self": "https://mydomain.atlassian.net/rest/api/2/user?accountId=000000000000000000000000",
      "accountId": "000000000000000000000000",
      "emailAddress": "user@mydomain.com",
      "avatarUrls": {
        "48x48": "",
        "24x24": "",
        "16x16": "",
        "32x32": ""
      },
      "displayName": "user USER",
      "active": true,
      "timeZone": "Europe/Paris",
      "accountType": "atlassian"
    }
  ]
}
```

IssueService.GetWatchers uses UserService.Get (https://godoc.org/github.com/andygrunwald/go-jira#UserService.Get). Without name key the operation returns something invalid.

Do you have the same problem as me ?

**Comment by ghostsquad** [comment]
hmm, the error doesn't represent a missing field. That error means that response is not valid json.

It's possible you are getting a different response from the library than you are from curl. 404's are sometimes returned instead of a 401, and the body of the response in that case could be HTML.

Can you make other requests successfully from the library?

**Comment by clementlecorre** [comment]
I did my test with curl and the lib go-jira.

`GetWatchers()` consists of two queries.

1. The first one is the rest/api/2/issue/%s/watchers which returns a payload with a missing field (username).
2. The second one I get a 404 error because the username field is missing.

I'm using the cloud jira version.

**Comment by ghostsquad** [comment]
#259 introduces a new method to support the `AccountId`. This might fix your issue?

**Comment by clementlecorre** [comment]
Yes! Thanks :)
