### ISSUE TITLE
Request an example of creating a Jira event for a custom field

### ISSUE THREAD

**Issue by 839588378** [andygrunwald/go-jira#257]
I don't know how to use this unkonw field，please give an example of creating a Jira event for a custom field,Thanks!!

![12](https://user-images.githubusercontent.com/23494356/75625221-f644ae00-5bf6-11ea-949d-89f647524b8f.jpg)
![image](https://user-images.githubusercontent.com/23494356/75625249-386def80-5bf7-11ea-858c-eb6791e40837.png)

**Comment by ghostsquad** [comment]
@839588378 see if this comment helps:

https://github.com/andygrunwald/go-jira/issues/178#issuecomment-478164887

**Comment by 839588378** [comment]
我这样试就可以了
//下拉框单选
custome["customfield_10209"] = map[string]string{"value": assessment}

	i := jira.Issue{
		Fields: &jira.IssueFields{
			//经办人
			Assignee: &jira.User{
				Name: jira_user,
			},
			Description: utf8toASCII(description),
			//问题类型：应用漏洞
			Type: jira.IssueType{
				ID: "10300",
			},
			//项目
			Project: jira.Project{
				ID: "10308",
			},
			//概要
			Summary: utf8toASCII(summary),
			//自定义字段
			Unknowns: custome,
		},
	}

**Comment by andygrunwald** [comment]
@839588378 Would you mind adding a PR with updating the docs on this? This would be helpful for a lot of people.

**Comment by fffinkel** [comment]
Re-opening stale comment! I'll be helping out with the project a bit, and Stale Bot is no more.

**Comment by fffinkel** [comment]
Re-opening stale comment! I'll be helping out with the project a bit and Stale Bot is no more, so we're re-opening tickets that were closed due to age.

**Comment by prerok-panshi** [comment]
I think that this issue can be closed? I think that @manuelbcd did what was required in the PR: https://github.com/andygrunwald/go-jira/pull/358
