### ISSUE TITLE
Search() triggers 400 Bad Request

### ISSUE THREAD

**Issue by willis7** [andygrunwald/go-jira#258]
I've been debugging my app most of the day, but it appears all paths lead to this package. Below is the smallest block of code to reproduce the error. It appears that any method I try to use results in the same error.

Please tell me it's me :-)

```
func TestRawCall(t *testing.T) {
	tp := api.BasicAuthTransport{
		Username: "apikeylabel",
		Password: "SECRET",
	}

	client, err := api.NewClient(tp.Client(), "https://mycompany.atlassian.net/")
	req, _ := client.NewRawRequest("GET", "rest/api/2/search?jql=project+%3D+JIR", nil)
	req.Header.Set("Content-type", "application/json")
	resp, _ := client.Do(req, nil)

	lines, _ := ioutil.ReadAll(resp.Body)
	println(string(lines))
}
```

> --- FAIL: TestRawCall (0.00s)
> panic: runtime error: invalid memory address or nil pointer dereference [recovered]
> 	panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x12b38b1]
> 
> goroutine 7 [running]:
> testing.tRunner.func1(0xc0000ea100)
> 	/usr/local/opt/go/libexec/src/testing/testing.go:874 +0x3a3
> panic(0x1309920, 0x15dbd00)
> 	/usr/local/opt/go/libexec/src/runtime/panic.go:679 +0x1b2
> github.com/andygrunwald/go-jira.(*Client).NewRawRequest(0x0, 0x136eaf0, 0x3, 0x137a2f5, 0x25, 0x0, 0x0, 0x100000001, 0xc00004cf38, 0x104ff88)
> 	/Users/sion/Code/go/pkg/mod/github.com/andygrunwald/go-jira@v1.12.0/jira.go:119 +0xc1
> github.com/willis7/jirabot/pkg/jira_test.TestRawCall(0xc0000ea100)
> 	/Users/sion/Code/jirabot/pkg/jira/client_test.go:57 +0x71
> testing.tRunner(0xc0000ea100, 0x1387258)
> 	/usr/local/opt/go/libexec/src/testing/testing.go:909 +0xc9
> created by testing.(*T).Run
> 	/usr/local/opt/go/libexec/src/testing/testing.go:960 +0x350
> FAIL	github.com/willis7/jirabot/pkg/jira	0.289s
> FAIL
> Error: Tests failed.

**Comment by ghostsquad** [comment]
Have you tried using the already implemented method to search?

https://github.com/andygrunwald/go-jira/blob/1946cac0fe6ee91f784e3dda3c12f3f30f7115b8/issue.go#L957

**Comment by willis7** [comment]
> Have you tried using the already implemented method to search?
> 
> https://github.com/andygrunwald/go-jira/blob/1946cac0fe6ee91f784e3dda3c12f3f30f7115b8/issue.go#L957

Yes, in fact, I only just noticed that I forgot to change the title of this issue. That was the original source of the question, but it was hard to share my example. I then realised all of the API calls were failing for me and the above snippet was the smallest block of code to share. 

To further investigate I created my own api client and that worked with the same JQL and credentials.

**Comment by ghostsquad** [comment]
@willis7 it looks like search calls this:

```go
	req, err := s.client.NewRequest("GET", u, nil)
	if err != nil {
		return []Issue{}, nil, err
	}
```

But your example uses raw request, and the last parameter of RawRequest is actually the body reader, which only allows `nil` because it's an interface, unlike this method, where the last parameter is the body itself, which it's valid not to provide.

Can you try using `NewRequest`?

**Comment by willis7** [comment]
Apologies for the delayed response. I have just tried this again (using the minimum viable code above) and I'm no longer having any problems. It's very bizarre.

I shall keep digging but for now, I will close and non-repeatable.
