### ISSUE TITLE
Support API for Getting Account ID for User given Key/Username

### ISSUE THREAD

**Issue by RKTMN** [andygrunwald/go-jira#262]
I didn't find anything in this repo that implements JIRA's `GET /rest/api/3/user/bulk/migration` endpoint. This would help us retrieve AccountIDs for the users given their username, which is now needed for Issue creation, etc...

**Comment by andygrunwald** [comment]
Indeed. This endpoint is not available at the moment.
Would you be able to create a Pull Request and implement his endpoint?

In the meantime, you can use [Call a not implemented API endpoint](https://github.com/andygrunwald/go-jira#call-a-not-implemented-api-endpoint).

**Comment by fffinkel** [comment]
Re-opening stale comment! I'll be helping out with the project a bit and Stale Bot is no more, so we're re-opening tickets that were closed due to age.

**Comment by RKTMN** [comment]
Looks like a fix was attempted: https://github.com/andygrunwald/go-jira/commit/436469b62d4d62037f380b38c918a13f4a5f0ab2
