### ISSUE TITLE
How does IssueType work when creating a new issue?

### ISSUE THREAD

**Issue by feorlen** [andygrunwald/go-jira#265]
I have some existing code to create new issues, but I'm only able to use a small number of IssueType name values, such as "Story", "Task", or "Bug". Is there a list of standard ones and others need to be handled in a different way? When I try others, for example "New Feature", I get "The issue type selected is invalid." 

I could understand if custom ones we created might have some special process. But "New Feature" is used in `mocks/project.json` so I thought at least that one would work. (And it exists in our Jira installation.)

How do I know which IssueType names are valid? I have the ID for the desired type, can I use that instead of the name? Thanks!

**Comment by feorlen** [comment]
I may have found my problem. I have the list of default feature types for my installation, but owners of some projects have removed various types for their project. So even if it's a default type globally, the one you want to specify also has to exist _for that specific project_.

**Comment by ghostsquad** [comment]
this is definitely a question for your Jira administrator, but it looks like you are on the right path.
