### ISSUE TITLE
UpdateIssue fails with 400 error code

### ISSUE THREAD

**Issue by sha4ever23** [andygrunwald/go-jira#266]
I am facing problem with updating an issue (to modify a custom field). Please find below the code snippet,

jiraIssue, resp, err := client.Issue.Get(jiraID, nil)

jiraIssue.Fields.Unknowns.Set("customfield_11206", "first update")

              var updopt jira.UpdateQueryOptions
              updopt.OverrideScreenSecurity = true
              updopt.OverrideEditableFlag = true
              _,_ , err = client.Issue.UpdateWithOptions(jiraIssue, &updopt )

Error,

Request failed. Please analyze the request body for more details. Status code: 400

**Comment by ghostsquad** [comment]
@sha4ever23 thanks for reporting this. There are other issues regarding custom fields. In particular, this comment might help you:

https://github.com/andygrunwald/go-jira/issues/178?ts=4#issuecomment-478167463

Please make sure to browse through existing issues prior to reporting new ones if possible. Though, it's clear that custom fields is a pain point for this library.

**Comment by sha4ever23** [comment]
Thank you for the response. I tried as below, now I get 405 error.

                new_cf := tcontainer.NewMarshalMap()
                new_cf["customfield_11206"] = "newVal"

                issue := jira.Issue{
                        Fields: &jira.IssueFields{
                                Unknowns: new_cf,
                        },
                }

                _, _, err = client.Issue.Update(&issue)

Request failed. Please analyze the request body for more details. Status code: 405

**Comment by sha4ever23** [comment]
Thank you for the response. I tried as below and I got 405 error

                new_cf := tcontainer.NewMarshalMap()
                new_cf["customfield_11206"] = "newVal"

                issue := jira.Issue{
                        ID: jiraID,
                        Fields: &jira.IssueFields{
                                Unknowns: new_cf,
                        },
                }

                _, _, err = client.Issue.Update(&issue)


"Request failed. Please analyze the request body for more details. Status code: 405"

**Comment by sha4ever23** [comment]
> Thank you for the response. I tried as below and I got 405 error
> 
> ```
>             new_cf := tcontainer.NewMarshalMap()
>             new_cf["customfield_11206"] = "newVal"
> 
>             issue := jira.Issue{
>                     ID: jiraID,
>                     Fields: &jira.IssueFields{
>                             Unknowns: new_cf,
>                     },
>             }
> 
>             _, _, err = client.Issue.Update(&issue)
> ```
> 
> "Request failed. Please analyze the request body for more details. Status code: 405"

I found my mistake. I set the Key instead of ID and now its working.
