### ISSUE TITLE
Field "username" was removed from /user/search by Atlassian

### ISSUE THREAD

**Issue by amossc** [andygrunwald/go-jira#272]
When trying to query a user by email address, the code in https://github.com/andygrunwald/go-jira/blob/master/user.go#L212 tries to query by field `username`, but Atlassian apparently has removed that field as part of their GDPR compliance support.

e.g. see the Q&A in https://community.atlassian.com/t5/Jira-questions/The-query-parameter-username-is-not-supported-in-GDPR-strict/qaq-p/1345106 referring to https://confluence.atlassian.com/cloud/blog/2018/06/say-goodbye-to-usernames-in-atlassian-cloud

I'm not 100% sure about the correct resolution, perhaps using `emailAddress` instead, or providing an option to override the query parameter name.

API documentation reference: https://developer.atlassian.com/cloud/jira/platform/rest/v3/?utm_source=%2Fcloud%2Fjira%2Fplatform%2Frest%2F&utm_medium=302#api-rest-api-3-user-search-get

NOTE: I see that `username` is still mentioned in that document, I suspect that this is an omission in the document update.

**Comment by ghostsquad** [comment]
ya, this looks related to some of the changes in #259 

We accept PRs!

**Comment by cynthiabaran** [comment]
Should this issue be closed now?
