### ISSUE TITLE
Unknown issue type encountered: option-with-child for

### ISSUE THREAD

**Issue by pz512** [andygrunwald/go-jira#275]
I use InitIssueWithMetaAndFields create , but "Unknown issue type encountered: option-with-child for"， not support option-with-child type，

"customfield_11712":{
            "allowedValues":Array[8],
            "hasDefaultValue":false,
            "name":"分类 & 子分类",
            "operations":[
                "set"
            ],
            "required":true,
            "schema":{
                "custom":"com.atlassian.jira.plugin.system.customfieldtypes:cascadingselect",
                "customId":11712,
                "type":"option-with-child"
            }

**Comment by andygrunwald** [comment]
Hey @pz512,

do you have a piece of sample code that we can reproduce this issue?

**Comment by pz512** [comment]
thanks, I reslove
I modify "issue.go" code, and add this
case "option-with-child":
			issueFields.Unknowns[jiraKey] = Option{
				Value: value,
}
