### ISSUE TITLE
Include new 'External Description' issue field

### ISSUE THREAD

**Issue by isobelormiston** [andygrunwald/go-jira#285]
It'd be great if an Issue object included the `External Description` field which appears for bugs in Jira, as well as the `Description` field.

**Comment by andygrunwald** [comment]
Hey @isobelormiston, do you have a link to the docs?

And maybe a piece of sample code to reproduce this / on how to use this?

**Comment by isobelormiston** [comment]
Hi @andygrunwald , thanks for getting back. 

For example, this JIRA issue has an External Description field:
https://smartsocietyservices.atlassian.net/browse/OC-129

At the moment, if we use `go-jira` to Get an issue (with `<Jira Client>.Issue.Get()`), we can see fields of the issue like e.g. `issue.Fields.Type.Name`, but to get hold of the 'External Description' at the moment it is a custom field and we can only see it with `issue.Fields.Unknowns["customfield_10098"]`. I was wondering if it can be changed into a named field.

Thanks!

**Comment by andygrunwald** [comment]
Hey @isobelormiston,
is this external description of a standard field of Jira? I was not able to find this in the official docs.

**Comment by isobelormiston** [comment]
It may not be a standard field actually, sorry - thanks all the same
