### ISSUE TITLE
Support of Go versions

### ISSUE THREAD

**Issue by andygrunwald** [andygrunwald/go-jira#290]
## Is your feature request related to a problem? Please describe.

Right now go-jira supports go v1.9. - go v1.14

## Describe the solution you'd like

Go's [Release Policy](https://golang.org/doc/devel/release.html#policy) only support the current version + the last two versions.

Question: Should we follow the same?

## Additional context

Right now, I am not aware of any breaking change from the Go language we faced.
However, it would provide clear guidance.

https://github.com/google/go-github is following the policy.

**Comment by ghostsquad** [comment]
I think it makes sense to support a limited subset. It keeps us moving forward, and saves time when it comes to trying to figure out a "backwards compatible" way to do something.

**Comment by ghostsquad** [comment]
@andygrunwald do you have to `/unstale` it or will any comment work?

**Comment by andygrunwald** [comment]
@ghostsquad No need touse the /unstale comment. I just used it to make my intentions clear.

**Comment by andygrunwald** [comment]
Fixed in https://github.com/andygrunwald/go-jira/pull/491
