### ISSUE TITLE
Jira 8

### ISSUE THREAD

**Issue by beorereleverion** [andygrunwald/go-jira#296]
Hello, can't use your great lib without any changes with jira 8 version

## Describe the solution you'd like

Jira 8 support

## Additional context

Do you plan Jira 8 support in nearest future?

**Comment by ghostsquad** [comment]
@beorereleverion can you explain what about Jira 8 is unsupported?

**Comment by beorereleverion** [comment]
i'm sorry i think that differnce between api v2 and v3 in worklogrecords.
i obviously have different struct to lib in my jira, something like:
type WorklogRecord struct {
	Self                  string           `json:"self,omitempty" structs:"self,omitempty"`
	Worker                string           `json:"worker,omitempty" structs:"worker,omitempty"`
	Author                *User            `json:"author,omitempty" structs:"author,omitempty"`
	Comment               string           `json:"comment,omitempty" structs:"comment,omitempty"`
	RemainingEstimate     string           `json:"remainingEstimate,omitempty" structs:"remainingEstimate,omitempty"`
	IncludeNonWorkingDays string           `json:"includeNonWorkingDays,omitempty" structs:"includeNonWorkingDays,omitempty"`
	Started               string           `json:"started,omitempty" structs:"started,omitempty"`
	EndDate               string           `json:"endDate,omitempty" structs:"endDate,omitempty"`
	TimeSpent             string           `json:"timeSpent,omitempty" structs:"timeSpent,omitempty"`
	TimeSpentSeconds      string           `json:"timeSpentSeconds,omitempty" structs:"timeSpentSeconds,omitempty"`
	BillableSeconds       string           `json:"billableSeconds,omitempty" structs:"billableSeconds,omitempty"`
	ID                    string           `json:"id,omitempty" structs:"id,omitempty"`
	OriginTaskId          string           `json:"originTaskId,omitempty" structs:"originTaskId,omitempty"`
	Properties            []EntityProperty `json:"properties,omitempty"`
}
i will talk with my jira administrator. Close issue please
