### ISSUE TITLE
Please keep HTTP Basic Auth capability as token-based-auth is not available on self-hosted JIRA instances (it's noted as depricated)

### ISSUE THREAD

**Issue by astockwell** [andygrunwald/go-jira#317]
Please keep HTTP Basic Auth capability as token-based-auth is not available on self-hosted JIRA instances (it's noted as depricated).

**Comment by fffinkel** [comment]
I've updated the README to be a bit more clear. We will not deprecate password auth for self-hosted Jira. Thanks @astockwell !
