### ISSUE TITLE
How to Update status and assignee for Jira tickets

### ISSUE THREAD

**Issue by vigkri** [andygrunwald/go-jira#318]
Hi all,

 Apologies if the query is a bit trivial. I am a beginner trying to use this module to automate Jira. I require help from the team to understand what is the syntax to change ticket statuses. Also, it would be helpful if somebody helps out on how to get the Assignee name for a Jira ticket (and change assignee).

Thank you.

**Comment by plilius** [comment]
In Jira, "status change" is called "transition". You should be able to use the `DoTransition()` method for simple status changed (without payload)
https://github.com/andygrunwald/go-jira/blob/f50cb07b297d79138b13e5ab49ea33965d32f5c1/issue.go#L1212 

or for passing the assignee in the same request use DoTransitionWithPayload()
https://github.com/andygrunwald/go-jira/blob/f50cb07b297d79138b13e5ab49ea33965d32f5c1/issue.go#L1237 
if you want to pass in a payload (such as assignee) in the same request. 

See this test for how to prepare the payload: https://github.com/andygrunwald/go-jira/blob/f50cb07b297d79138b13e5ab49ea33965d32f5c1/issue_test.go#L859
For assignee in the payload, it's should be something along the lines of:
```
        customPayload := map[string]interface{}{
		"fields": map[string]interface{}{
			"assignee": [string]string{
				"key": userKey,
				"name": userName,
			},
		},
		"transition": TransitionPayload{
			ID: transitionID,
		},
	}
```

Hope this helps!

**Comment by plilius** [comment]
Also, to get the assignee name for an issue, use GetIssue() method:
https://github.com/andygrunwald/go-jira/blob/146229d2ab58a3fb128ddc8dcbe03aff72e20857/sprint.go#L121

**Comment by fffinkel** [comment]
I've added an issue transition example to the README. Thanks so much for your help @plilius !
