### ISSUE TITLE
Getting weird auth Error : stream error: stream ID 1; REFUSED_STREAM"

### ISSUE THREAD

**Issue by meirwah** [andygrunwald/go-jira#32]
I Test vs. a cloud instance of Jira.
Any idea?

**Comment by andygrunwald** [comment]
Hey @meirwah,
can you please post your code to show what you are doing?
And which cloud instance? Is this public?

**Comment by meirwah** [comment]
sure,
```
cl, err := jira.NewClient(nil, "https://demisto.atlassian.net/")
cl.Authentication.AcquireSessionCookie(username, password)
```

**Comment by meirwah** [comment]
it's jira as a service instance...

**Comment by meirwah** [comment]
full error:
```
Received unexpected error "Auth at JIRA instance failed (HTTP(S) request). Post https://demisto.atlassian.net/rest/auth/1/session: stream error: stream ID 1; REFUSED_STREAM"
```

**Comment by meirwah** [comment]
@andygrunwald any idea?

**Comment by andygrunwald** [comment]
@meirwah Sorry, no idea right now. Did you solved the problem in the meantime?

**Comment by meirwah** [comment]
nope :(
impl the lib by myself in the end

**Comment by andygrunwald** [comment]
How did you do this? What did you differently as go-jira?
Can you maybe share your auth code / request code here?
Maybe we can see the difference there.

**Comment by rnewton** [comment]
I encountered this error today as well. My code is nothing special:

```go
client, err := jr.NewClient(nil, viper.GetString("jira.baseurl"))
if err != nil {
	log.Fatal(err)
}
```

This works when I'm running locally, but not when running in a docker container.

**Comment by andygrunwald** [comment]
@rnewton Any chance that i can reproduce / get the same setup for your cloud jira? To reproduce this error?

**Comment by andygrunwald** [comment]
Any news @rnewton ?

**Comment by gha** [comment]
@andygrunwald Also getting this error for a basic implementation, running this on my mac

```
client, err := jira.NewClient(nil, "https://instance.atlassian.net/")
if err != nil {
    return nil, err
}

res, err := client.Authentication.AcquireSessionCookie(user, pass)
if err != nil {
    log.Println("Auth result: ", res)
    return nil, err
}

return client, nil
```

**Comment by rnewton** [comment]
Sorry, I missed the initial mention. I wasn't able to fix this error, only work around it by building locally (on osx with build flags for linux) and pushing the binary to docker. I _think_ it has to do with SSL and passing in an `http.Client` with modified options might work.

**Comment by meirwah** [comment]
yes I think @rnewton is right.. 
and you need to add this:
```
tls.Config{InsecureSkipVerify: true}
```
To the http client

**Comment by andygrunwald** [comment]
This seems to work now with a custom http client, right?
If i am wrong, feel free to reopen this.
