### ISSUE TITLE
unable to use CustomField , Attachments And Adding it to EPIC  while creating Jira TIcket

### ISSUE THREAD

**Issue by NehaSachan** [andygrunwald/go-jira#330]
`customfields := tcontainer.NewMarshalMap()
	customfields = tcontainer.MarshalMap{
		// "customfield_13100": "API-125",
		"customfield_15400": "Testiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
	}
	i := jira.Issue{
		Fields: &jira.IssueFields{
			// Expand: "customfield_16053",
			// Epic: &jira.Epic{
			// 	Key: "API-125",
			// },
			// Parent: &jira.Parent{
			// 	Key: "API-125",
			// },
			Labels: []string{"testing", "tryingtoaddepic"},
			// "customfield_13100": "API-125",
			Description: "Test Issue",
			Type: jira.IssueType{
				Name: "Bug",
			},
			Project: jira.Project{
				Key: "API",
			},
			// Attachments: []*jira.Attachment{
			// 	{
			// 		Filename: "test.html",
			// 		Content:  "file.pdf",
			// 	},
			// },
			Summary:  "Just a demo issue[Testing]",
			Unknowns: customfields ,
		},
	}

`

above is my code, please let me know what i had done wrong here ?

**Comment by NehaSachan** [comment]
Hi team
Please help out as stuck to this issue..

**Comment by NehaSachan** [comment]
@andygrunwald please look into it....


{
    "fields": {
        "project": {
            "key": "XXXXXXX"
        },
        "summary": "just a demo test",
        "issuetype": {
            "name": "Bug"
        },
        "assignee": {
            "name": "Neha Sachan"
        },
        "customfield_16053" : {"value": "green", "child": {"value":"blue"} },
        
        "attachment": [
            {
                "filename": "handon.txt",
                "mimeType": "text/plain",
                "content": "/mnt/c/Users/nsachan/Documents/frontdoor/handon.txt"
            }
        ]
    }
}


getting this for custom fields and attachment..
{
    "errorMessages": [],
    "errors": {
        "customfield_16053": "Field 'customfield_16053' cannot be set. It is not on the appropriate screen, or unknown.",
        "attachment": "Field does not support update 'attachment'"
    }
}

**Comment by benjivesterby** [comment]
@NehaSachan It looks like your JIRA screen doesn't have the custom field added to it for the operation you're attempting. 

See: https://community.atlassian.com/t5/Jira-questions/quot-Field-customfield-10012-cannot-be-set-It-is-not-on-the/qaq-p/664236

Please verify that the issue screen has this custom field added to it (in the UI) otherwise the JIRA API from Atlassian will not allow you to set the field.

**Comment by andygrunwald** [comment]
Hey @NehaSachan,

thanks for your issue. I would like to help you to solve your issue, however, my and the time of the other contributors does not always allow quick responses. Please understand, that this library is provided as open-source for you and others to use (free of charge) and was created mostly in the spare time of me and other contributors.

If you require a timely response or support to solve your problem, please reach out privately via email to me, @ghostsquad, @fffinkel, and other contributors. There we can work on a professional arrangement or a support/consultancy contract to help you to master your challenges.

PS: Thanks @benjivesterby for jumping in! Much appreciated.

**Comment by NehaSachan** [comment]
@andygrunwald thankx for the support.
i am now directly calling the jira rest api.
