### ISSUE TITLE
Consider upgrading version of jwt-go to fix security vulnerability

### ISSUE THREAD

**Issue by lodi-g** [andygrunwald/go-jira#343]
Hi,

The dependency jwt-go has a security vulnerability in all versions <4.0.0: https://github.com/dgrijalva/jwt-go/issues/428 .
Please consider upgrading to the latest version (v4.0.0-preview1) or switching for another library.

Thanks!

**Comment by benjivesterby** [comment]
@andygrunwald @ghostsquad Perhaps we should set up dependabot so that it can auto-pr package upgrades and merge if the CI passes?

**Comment by andygrunwald** [comment]
<img width="965" alt="Screen Shot 2021-02-08 at 16 24 16" src="https://user-images.githubusercontent.com/320064/107240380-219c6380-6a2a-11eb-82a8-775ef1d48375.png">

Everything is activated already. Is there anything else to do from our side?

Is there a way to check if this vuln is already caught up by the bot?

**Comment by benjivesterby** [comment]
Hmm I'm not sure. Do you have it setup here? https://app.dependabot.com/accounts/andygrunwald

**Comment by andygrunwald** [comment]
Thanks @benjivesterby 
Dependabot is now working. PRs are incoming. Until now, no one for go-jwt.
Maybe we wait a bit and/or do it by hand :)

**Comment by benjivesterby** [comment]
@andygrunwald no problem. I would suspect that it will auto-PR it. When I've had a security vuln pop on my libs before it took a couple days before dependabot updated. If not that we can keep an eye and do it manually.

**Comment by lodi-g** [comment]
Thank you for your reactivity!
Please keep in mind that the newest version of jwt-go is a "preview" version so it might not be publised at the "latest" but more in a beta form, we should make sure it does not break anything before upgrading.

**Comment by yarlson** [comment]
@andygrunwald https://github.com/dgrijalva/jwt-go has been abondoned (see https://github.com/dgrijalva/jwt-go/issues/462). In order to fix the vulnarability we have to switch to a community driven fork https://github.com/golang-jwt/jwt . The issue has been fixed in https://github.com/golang-jwt/jwt/pull/12
