### ISSUE TITLE
Is support for creating issues with custom fields available?

### ISSUE THREAD

**Issue by mdamir** [andygrunwald/go-jira#35]

**Comment by andygrunwald** [comment]
@mdamir @shannonrdunn Not in master (yet), but it seems that #36 is tackling this issue.
Does it solve your use case?

**Comment by andygrunwald** [comment]
Should be solved with the merge of #36.
If not please reopen.

**Comment by dontrebootme** [comment]
@andygrunwald Is there a way to show a simple example of issue create with a custom field? I'm not understanding, do I need to create new instance of tcontainer.MarshalMap?

**Comment by andygrunwald** [comment]
@dontrebootme You don`t have to use the `tcontainer.MarshalMap`.

You can use the [InitIssueWithMetaAndFields](https://godoc.org/github.com/andygrunwald/go-jira#InitIssueWithMetaAndFields) function.
See here for a real world example: https://github.com/cloudflare/complainer/blob/master/reporter/jira.go#L125

**Comment by kcrexchan** [comment]
@andygrunwald , I'm new to go and jira, can you show some example of how to retrieve the custom fields with go-jira? Thank you.

**Comment by lwoj17** [comment]
What would the correct syntax be for creating an issue with a custom field and that data needs to be in an array?

{"errorMessages":[],"errors":{"IT Teams":"data was not an array"}}

Unknowns: tcontainer.MarshalMap{ 
    "customfield_11882": "Something",
},

**Comment by rbriski** [comment]
This issue is closed.  Please open another issue with the question and provide the code that's failing.
