### ISSUE TITLE
Errors during issue creation not reported correctly

### ISSUE THREAD

**Issue by bidesh** [andygrunwald/go-jira#37]
If the create issue fails, then jira returns a json format with errors. But this cannot be retrieved in current solution because even though the reponse is returned, it is already read from. And the unmarshalling of response is done in Issue struct. This doesn't have the keys and thus the detailed error message is lost. 

Jira response details for create can be found here:
https://docs.atlassian.com/jira/REST/server/#api/2/issue-createIssue

**Comment by andygrunwald** [comment]
This was fixed in #39
