### ISSUE TITLE
assignee field while creating jira ticket fails with 400

### ISSUE THREAD

**Issue by ptripathi-twilio** [andygrunwald/go-jira#373]
## Describe the bug

When I try to assign a ticket to some while creating it, zapi fails with 4000 bad request.

 jira create API payload log looks like this:
`"fields":{"assignee":{"Password":"","name":"svc.koalat-jira"},"issuetype":{"name":"Test"},"labels":["MyMy"],"project":{"id":"23432"},"reporter":{"Password":"","name":"fgvg.rtf"},"summary":"TestVoid"}}`

but I get a 400 error with msg like this:

`{"errorMessages":[],"errors":{"assignee":"Field 'assignee' cannot be set. It is not on the appropriate screen, or unknown."} `

## To Reproduce

create a ticket with assignee field as `assignee`

## Expected behavior

should create the ticket

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* go-jira version (git tag or she): latest
* Go version (`go version`): latest
* Jira type (cloud or on-premise): on prem

**Comment by Dynatrace-Adam-Gardner** [comment]
Assignee and Reporter need to be user IDs not usernames

**Comment by ctreminiom** [comment]
It seems the user you're using to authenticate the call doesn't have the **Assignable User** permission or the fields are not in the **Issue Create** screen.  @Dynatrace-Adam-Gardner the User ID (account-ID) is required only on the Cloud version, on Jira On-Prem is the _Username_ value

**Comment by manuelbcd** [comment]
@benjivesterby, @andygrunwald  I think this issue is resolved and can be closed

Best.

**Comment by benjivesterby** [comment]
@manuelbcd Sounds good
