### ISSUE TITLE
Love your Library, great work, keep it up

### ISSUE THREAD

**Issue by percybolmer** [andygrunwald/go-jira#394]
## Describe the bug
Just wanted to share my love for the Repo, You guys have done a solid job! Thanks!

## Possible Solution
Keep it up
Close this issue after receiving love
## Additional context

Wanted to spread my love for your Repo, so I've published an article about using Jira in Golang in which I use your library to showcase the basics. 
Just want to spread the love.
Hopefully, it's to your liking. Here is a draft. 
https://betterprogramming.pub/automate-jira-cloud-workflow-with-golang-2de29828aad6

**Comment by andygrunwald** [comment]
Thanks @percybolmer for the kind words.
I keep this issue open for a few more days that other maintainers also can see your appreciation.
