### ISSUE TITLE
Support for authenticating with Personal Access Tokens on Jira Data Center

### ISSUE THREAD

**Issue by evilnerd** [andygrunwald/go-jira#421]
## Is your feature request related to a problem? Please describe.

Since the latest LTS version of Jira Data Center, we can now issue Personal Access Tokens and use those to authenticate (instead of clear-text username/passwords) -- which is very convenient for running automated tools that e.g. gather some information from Jira overnight.

## Describe the solution you'd like

Support for PAT authentication, via a new AuthTransport (e.g. PATAuthTransport), which sits next to e.g. BasicAuthTransport.

## Describe alternatives you've considered

I've tried to use Basic auth, substituing the password with the token, but Jira expects the token in an `authentication` header. Just works differently.

**Comment by evilnerd** [comment]
I have built a solution for this, I just wanted to connect it to a feature request. Please assign it to me.

**Comment by andygrunwald** [comment]
Sounds good. Assigned. Thanks @evilnerd!

**Comment by badnetmask** [comment]
I hope this helps getting this feature pushed. I tried the code in https://github.com/andygrunwald/go-jira/pull/422, and it works fine for me. Thank you.

**Comment by evilnerd** [comment]
Thanks @badnetmask ! -- I also hope this helps, because I want to release my work project with a version of the lib that supports PATs :)
