### ISSUE TITLE
Unable to create an issue in jira using this API

### ISSUE THREAD

**Issue by ap040298** [andygrunwald/go-jira#427]
we are currently using the Jira v7.3.6 server. While using the API I was able to connect to the server and also able to retrieve the projects as well in the Jira application.  But I was unable to create an issue and getting the error message as page not found(Screenshot is attached)
![image](https://user-images.githubusercontent.com/81238982/146542979-a8fe3152-15ef-493b-823f-2bc8d2e1fb7b.png)
Can someone help me out to resolve this ? or is this API supported for only the jira version mentioned in the requirements ?

**Comment by ap040298** [comment]
Some more details:
jira version=>7.3.6
Go version=>1.17.5
OS: windows
Using jira cloud which is deployed as an operator in kubernetes.

Can you please provide me an update on this issue soon? @andygrunwald

**Comment by benjivesterby** [comment]
@ap040298 Please provide code samples. Nothing in your comment indicates how can debug this. Also both of us are busy on other projects and review these issues when we have time. You're always welcome to submit a  PR for a fix if there is a bug in the library.

**Comment by andygrunwald** [comment]
@ap040298 I second what @benjivesterby wrote.
If you need professional support, we are able to provide you with an offer based on your project details. You are also able to sponsor this issue via GitHub sponsors. Based on this we can provide fast response times. Thanks for understanding.

**Comment by ap040298** [comment]
package main import ( 	"fmt" 	"github.com/andygrunwald/go-jira" ) func main() { 	base := "https://my.jira.com" 	tp := jira.BasicAuthTransport{ 		Username: "username", 		Password: "token", 	} 	jiraClient, err := jira.NewClient(tp.Client(), base) 	if err != nil { 		panic(err) 	} 	i := jira.Issue{ 		Fields: &jira.IssueFields{ 			Assignee: &jira.User{ 				Name: "myuser", 			}, 			Reporter: &jira.User{ 				Name: "youruser", 			}, 			Description: "Test Issue", 			Type: jira.IssueType{ 				Name: "Bug", 			}, 			Project: jira.Project{ 				Key: "PROJ1", 			}, 			Summary: "Just a demo issue", 		}, 	} 	issue, _, err := jiraClient.Issue.Create(&i) 	if err != nil { 		panic(err) 	} 	fmt.Printf("%s: %+v\n", issue.Key, issue.Fields.Summary) }


The same part of code you have in the readme file for creating ticket is throwing error while creating an issue. The error is thrown at the exception part panic(err). In terminal it shows please analyse the request body @andygrunwald @benjivesterby

**Comment by benjivesterby** [comment]
@ap040298 Please update your code with a code block so we can see it properly formatted. It's very difficult to read just pasted into the text field. Here is a guide: https://www.markdownguide.org/extended-syntax/#fenced-code-blocks

**Comment by ap040298** [comment]
`package main

import (
	"fmt"

	"github.com/andygrunwald/go-jira"
)

func main() {
	sendmsgtojira()
}

func sendmsgtojira() {
	base := "https://temporal.atlassian.net"
	tp := jira.BasicAuthTransport{
		Username: "myemail@gmail.com",
		Password: "mytoken generated from jira API token",
	}

	jiraClient, err := jira.NewClient(tp.Client(), base)
	fmt.Println("jiraClient", jiraClient)
	if err != nil {
		panic(err)
	}

	i := jira.Issue{
		Fields: &jira.IssueFields{
			Description: "Test Issue",
			Type: jira.IssueType{
				Name: "Bug",
			},
			Project: jira.Project{
				Key: "AT-3",
			},
		},
	}
	issue, _, err := jiraClient.Issue.Create(&i)
	if err != nil {
		panic(err)
	}

	fmt.Printf("%s: %+v\n", issue.Key, i.Fields.Summary)
}
`

**Comment by ap040298** [comment]
@benjivesterby @andygrunwald The above code is the one i have used to create an issue in Jira, it is passing to the error block and returns the 400 bad request at the lines`issue, _, err := jiraClient.Issue.Create(&i)
if err != nil {
	panic(err)
}`

**Comment by benjivesterby** [comment]
@ap040298 your base URL looks like it's probably the issue. If I'm not mistaken `temporal.atlassian.net` will parse as `http` not `https`. Can you try updating your base url to include `https://` at the beginning and see if you still get a 400 response?

**Comment by ap040298** [comment]
My baseurl is https://accuknoxtemporal.attlasian.net

**Comment by ap040298** [comment]
Iam passing it as https only, can you correct me what iam doing exactly wrong out here

**Comment by benjivesterby** [comment]
@ap040298 Your link above has `atlassian.net` misspelled. try `https://accuknoxtemporal.atlassian.net`

**Comment by ap040298** [comment]
> @ap040298 Your link above has `atlassian.net` misspelled. try `https://accuknoxtemporal.atlassian.net`

tried the similar error facing @benjivesterby

**Comment by benjivesterby** [comment]
@ap040298 can you try using [Postman](https://www.postman.com/downloads/) and see if you are still getting the 400 error?

**Comment by ap040298** [comment]
> @ap040298 can you try using [Postman](https://www.postman.com/downloads/) and see if you are still getting the 400 error?
![image](https://user-images.githubusercontent.com/81238982/146673472-70eb0609-963f-44c9-879c-24a6188219e6.png)
Iam getting 200 status OK in postman. Also Iam able to create a ticket via postman API too. @benjivesterby

**Comment by benjivesterby** [comment]
@ap040298 please show the issue creation. The screen shot provided shows 200 because it's just querying your jira portal URL which will provide 200 as long as the portal exists. I need to see the API response with JSON showing a non-400 error to debug. Please also make sure it shows the API path you're using.

**Comment by ap040298** [comment]
> @ap040298 please show the issue creation. The screen shot provided shows 200 because it's just querying your jira portal URL which will provide 200 as long as the portal exists. I need to see the API response with JSON showing a non-400 error to debug. Please also make sure it shows the API path you're using.

![image](https://user-images.githubusercontent.com/81238982/146674138-10e2c2a8-fc61-415c-bc47-a3bace22fb15.png)
`{
    "fields": {
       "project":
       {
          "key": "AT"
       },
       "summary": "TICKET CREATED SUCCESSFULLY-1",
       "description": {
           "type":"doc",
           "version":1,
           "content":[
               {
                   "type":"paragraph",
                   "content":[
                       {
                           "type":"text",
                           "text":"description"
                       }
                   ]
               }
           ]
       },
       "issuetype": 
       {
          "name": "Story"
       }
   }
}`

This is the request  body iam using which is used in postman 

![image](https://user-images.githubusercontent.com/81238982/146674198-3271e258-b2c1-4a64-bc9a-1617c2fb3882.png)

**Comment by andygrunwald** [comment]
@ap040298 Do you find your answer?
If yes, can you share it with the community?

**Comment by ap040298** [comment]
Hi @andygrunwald , it is version issue..you have used the rest API version 2.0..in the package ..where I have used the v3.0 .That is the cause for my query unable to create an issue .I have changed the API version to v2.0 hence it worked . That's it!!
