### ISSUE TITLE
Add changelog

### ISSUE THREAD

**Issue by dobegor** [andygrunwald/go-jira#45]
It would be nice to have a way to provide "expand" parameter to get issue's changelog, i.e.
`http://your-jira-server/rest/api/2/issue/ISSUE-11?expand=changelog`

**Comment by andygrunwald** [comment]
@dobegor True. This is not supported yet.
Right now i don`t have the time to implement it.

For the implementation i would choose the package `github.com/google/go-querystring/query`.
With this you are able to define "Option"-Structs with `url` tags like here: https://github.com/andygrunwald/go-gerrit/blob/master/projects.go#L169

Based on this struct you can implement an `addOptions` like here: https://github.com/andygrunwald/go-gerrit/blob/master/gerrit.go#L438

And here is an example how you would call this `addOptions` function: https://github.com/andygrunwald/go-gerrit/blob/eba8c6989a186784d5239df46ba5d166d7c17fdd/projects_tag.go#L22

Does this make sense to you?
Would you mind to do a PR?

**Comment by andygrunwald** [comment]
Hey @dobegor,
@lycis was so kind and added ChangeLog functionality in #58
I hope this solved your request. If not feel free to add a new issue.
