### ISSUE TITLE
Bearer auth method

### ISSUE THREAD

**Issue by fleimkeipa** [andygrunwald/go-jira#470]
## Feature describe

go-jira have only basic auth and cookie session auth. After jira version 8.14.0 we need to bearer token auth method.
I use jira server version 9.1.0.

```go

	// Set authentication information
	if c.Authentication.authType == authTypeSession {
		// Set session cookie if there is one
		if c.session != nil {
			for _, cookie := range c.session.Cookies {
				req.AddCookie(cookie)
			}
		}
	} else if c.Authentication.authType == authTypeBasic {
		// Set basic auth information
		if c.Authentication.username != "" {
			req.SetBasicAuth(c.Authentication.username, c.Authentication.password)
		}
	}


```

## Describe the solution you'd like

We can add request header bearer method like basic auth.

[Using Personal Access Tokens](https://confluence.atlassian.com/enterprise/using-personal-access-tokens-1026032365.html
)

**Comment by andygrunwald** [comment]
We support the usage of Personal Access Tokens. See https://github.com/andygrunwald/go-jira/blob/master/jira.go#L389-L391
