### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by crisarceramos** [andygrunwald/go-jira#52]
Hi,
I'm getting below error from calling jiraClient.Authentication.AcquireSessionCookie. Do I need certificate?
panic: Auth at JIRA instance failed (HTTP(S) request). Post https://myjira.com/rest/auth/1/session: x509: certificate signed by unknown authority

**Comment by andygrunwald** [comment]
At the first look this seems to be a issue with the SSL cert.
Do you have a little bit more information? About OS, Golang version, URL, example code, etc?

Maybe have a look at https://groups.google.com/forum/#!topic/golang-nuts/v5ShM8R7Tdc

Can you try if this might be running with `tls.Config{InsecureSkipVerify: true}` ?
This was mentioned in #32

**Comment by mgilbir** [comment]
If you are on OSX, there is some weird behavior when handling certs stored in the keychain.

You may want to take a look at https://github.com/hashicorp/go-rootcerts instead of skipping the TLS verification.

**Comment by crisarceramos** [comment]
Thanks @andygrunwald, your suggestion works! Added below line before calling NewClient.

import ("net/http"; "crypto/tls")

tr := &http.Transport{
	TLSClientConfig: &tls.Config{InsecureSkipVerify : true},
}
client := &http.Client{Transport: tr}

**Comment by andygrunwald** [comment]
Thats good to here @crisarceramos :)

**Comment by aniztar** [comment]
@andygrunwald Had a similar problem. Your answer helped me too. Thanks!

**Comment by andygrunwald** [comment]
@aniztar Glad to hear that! Good luck with your project.

**Comment by EnchanterIO** [comment]
Lol @andygrunwald, nice to see you again outside of trivago. You just solved my problem. 

```go
tr := &http.Transport{
TLSClientConfig: &tls.Config{InsecureSkipVerify : true},
}
client := &http.Client{Transport: tr}
```

Worked perfectly.

**Comment by andygrunwald** [comment]
Thanks @EnchanterIO  :)

**Comment by pureugong** [comment]
@andygrunwald 
Thx! I fixed the similar issue!

**Comment by nansuri** [comment]
hi all, i got this error as well in my project using go-jira, could anyone show me how to implement the TLS skip code?

**Comment by andygrunwald** [comment]
@nansuri Can you post your code snippet to showcase the problem?

**Comment by topoko123** [comment]
> 

Thanks, you help me and our team <3
