### ISSUE TITLE
Question regarding closing jira.Response body

### ISSUE THREAD

**Issue by novembrea** [andygrunwald/go-jira#582]
Hello! I'm not super proficient with Go and am a bit worried about handling `*jira.Response`, I remember reading that it's always a caller's responsibility to close the response body, so considering the following code

```
	resp, err := service.jira.Issue.DoTransition(issue.ID, nextStatus)
	if err != nil {
		return err
	}

	defer resp.Body.Close()

	resp, err = service.jira.Issue.UpdateAssignee(issueKey, &jira.User{
		AccountID: assignee.JiraID,
	})

	if err != nil {
		return err
	}

	defer resp.Body.Close()
```

Do I always have to explicitly close `*jira.Response` body, even if I'm not using it, i.e: won't omit the response by writing it this way  `_, err := service.jira.Issue.DoTransition(issue.ID, nextStatus)` lead to memory leaks in the long run?

Thanks in advance!

**Comment by vladimir-ch** [comment]
Your example code is correct and in case of both `DoTransition` and `UpdateAssignee` the caller should close the response Body.

> I remember reading that it's always a caller's responsibility to close the response body

That's correct when you're using `http.Client`. However, go-jira's `Client.Do` has an additional logic that sometimes closes the response Body for you.

You should check the documentation of the methods that you use and close the response Body if it says so.

`DoTransition`'s doc comment was missing this instruction, so I've just submitted #590 that adds it.
