### ISSUE TITLE
Query all open issues of a project

### ISSUE THREAD

**Issue by crisarceramos** [andygrunwald/go-jira#59]
@andygrunwald do u have any sample of this? thanks!

**Comment by andygrunwald** [comment]
You can use the [Search method](https://godoc.org/github.com/andygrunwald/go-jira#IssueService.Search) ([Search @ JIRA-Docs](https://developer.atlassian.com/jiradev/jira-apis/jira-rest-apis/jira-rest-api-tutorials/jira-rest-api-example-query-issues)) for this incl. a JQL query.
Here is an example:

```go
package main

import (
	"fmt"
	"github.com/andygrunwald/go-jira"
)

func main() {
	jiraClient, _ := jira.NewClient(nil, "https://issues.apache.org/jira/")

	jql := "project = ZooKeeper and status = Open"

	issues, resp, err := jiraClient.Issue.Search(jql, nil)
	if err != nil {
		fmt.Println(err)
		panic(resp.StatusCode)
	}

	for _, issue := range issues {
		fmt.Printf("%s: %+v\n", issue.Key, issue.Fields.Summary)
	}
}
```

Is this what you are looking for?

**Comment by andygrunwald** [comment]
No feedback since ~1 month.
@crisarceramos If this don't solve your problem, please let me know.
