### ISSUE TITLE
Undeclared variable on readme code sample to update jira ticket status

### ISSUE THREAD

**Issue by roshanraj** [andygrunwald/go-jira#594]
## What happened?

Sample code snippet to update jira issue status on readme has undeclared variable, which probably was to hold issue id that would be used across the sample

## What did you expect to happen?
consistency either we repeat the string across the code or have it assigned to a variable and then used across code

## How can we reproduce it (as minimally and precisely as possible)?
By reading the code at readme

Minimal code helps us to identify the problem faster.

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* go-jira version (git tag or sha):
* Go version (`go version`):
* Jira type (cloud or on-premise):
* Jira version / Api version:

**Comment by andygrunwald** [comment]
Fixed in https://github.com/andygrunwald/go-jira/pull/593
