### ISSUE TITLE
How can i parse SocOptionImpl custom field?

### ISSUE THREAD

**Issue by ItamarShDev** [andygrunwald/go-jira#598]
When i call the ticket i get `SocOptionImpl{label='some-label', value='some-value'}`

How can i parse it?

**Comment by andygrunwald** [comment]
@ItamarShDev Can you provide a full but minimal code example?

And please provide basic information like

* go-jira version (git tag or sha):
* Go version (`go version`):
* Jira type (cloud or on-premise):
* Jira version / Api version:

Thank you

**Comment by andygrunwald** [comment]
@ItamarShDev Did you find a solution for your problem?
I think this would help others in the community as well.

**Comment by ItamarShDev** [comment]
@andygrunwald Thank you for making sure i will write my solution. I have meant to write a comment but forgot!

What i did (and it might be a bad solution) is this:
```golang
func (s *service) getFieldSocOptionImplValue(ticketFields *jira.IssueFields, fieldID string) string {
	var fieldValue string
	field, exist := ticketFields.Unknowns.Value(fieldID)
	if exist {
		fieldMap, ok := field.([]interface{})
		if ok {
			re := regexp.MustCompile(`value='(.*)'`)
			for _, v := range fieldMap {
				matches := re.FindStringSubmatch(v.(string))
				fieldValue = matches[1]
			}
		}
	}
	return fieldValue
}
```
