### ISSUE TITLE
Add support for issue deletion

### ISSUE THREAD

**Issue by niallo** [andygrunwald/go-jira#60]
Thanks for writing this JIRA library. I noticed that issue deletion is not supported. It would be really nice to have this. Cheers.

**Comment by andygrunwald** [comment]
Hey @niallo,

you are right. Good catch. This functionality is not implemented (yet).
But i think this is useful. I would be happy to accept a pull request for this.
Here are a few notes that might get you or someone else who is willing to contribute up to speed:

* The requested functionality is documented at [Delete Issue @ JIRA Docs](https://docs.atlassian.com/jira/REST/cloud/#api/2/issue-deleteIssue)
* A similar function (not for issues, but for "Boards") is implemented already in go-jira: [DeleteBoard @ `BoardService`](https://github.com/andygrunwald/go-jira/blob/a7647f3c7b3605a6fd178aba217adba6131eb4b8/board.go#L130)
* The code is (nearly) the same like the one in BoardService with the adjustments to the `IssueService` and the API-URL
* How a functionality for the `IssueService` will be implemented can be seen at [Get @ `IssueService`](https://github.com/andygrunwald/go-jira/blob/a7647f3c7b3605a6fd178aba217adba6131eb4b8/issue.go#L426)
* If you want to go even further a unit test for this is highly welcome!
* Such a unit test needs to be implemented in the [`issue_test.go`](./issue_test.go) file
* How a unit test for a DELETE call can look like is visible at [`TestBoardService_DeleteBoard`](https://github.com/andygrunwald/go-jira/blob/a7647f3c7b3605a6fd178aba217adba6131eb4b8/board_test.go#L136)

**Comment by andygrunwald** [comment]
Was fixed in #65
Thanks go to @ggrpmnn

**Comment by ggrpmnn** [comment]
:+1:
