### ISSUE TITLE
Basic auth support

### ISSUE THREAD

**Issue by fkrauthan** [andygrunwald/go-jira#61]
Hey,

I am relatively new to go but as I understand your library suppose to support basic auth connection with Jira. Your documentation for session cookie authentication even recommends to use basic auth. But I do not see any place to provide username and password to this library. I looked into go documentation but they say I would need to provide a username and password for each request object so I can't even set it globally on the http connection that I could pass in. 

Can some one please advice?

**Comment by Smadarl** [comment]
I had some luck with this:
http://grokbase.com/t/gg/golang-nuts/1293s1j54z/go-nuts-how-to-do-basic-authentication

I did notice though, that it only works for the first call after setting it up, like so:
client := &http.Client{}
client.Transport = &http.Transport {
	Proxy: func(req *http.Request) (*url.URL, error) {
		req.SetBasicAuth("username", "password")
		return nil, nil
	},
}
jiraClient, err = jira.NewClient(client, settings.Url)

My first call searches for certain issues (jiraClient.Issue.Search).  It returns the issues just fine.  The second call requests a list of transitions (jiraClient.Issue.GetTransitions).  If I just use the same object (jiraClient) that I used for the issue list, for some reason it fails on auth.  I don't think the Authorization header is getting sent.  If I create a new jiraClient object as above, it works again.  I haven't been able to figure out why a client won't set the auth header after the first call.

**Comment by fkrauthan** [comment]
Hmm I think the Authorization helper should be extended to directly pass in basic auth parameters. And then the library can pass it thru to each request object.

**Comment by perolausson** [comment]
Just curious, why not use the cookie based approach?

**Comment by fkrauthan** [comment]
Because even the library documentation here recommends not to use it^^

**Comment by Smadarl** [comment]
So I just added these few lines of code to jira.go, and it worked perfectly:
`
type basicAuth struct {
	username string
	password string
}
...

type Client struct {
    bAuth basicAuth

...


func (c *Client) SetBasicAuth(username, password string) {
	c.bAuth.username = username
	c.bAuth.password = password
}

...

func (c *Client) Do(req *http.Request, v interface{}) (*Response, error) {
	if len(c.bAuth.username) > 0 {
		req.SetBasicAuth(c.bAuth.username, c.bAuth.password)
	}

`

**Comment by perolausson** [comment]
If you access it over http yes, can understand it. Otherwise, if over https I don't see any issue.

**Comment by fkrauthan** [comment]
Well regardless. The library claims to support basic auth but right now it does not. So it is definitely a bug.

**Comment by perolausson** [comment]
I think the code missing in go-jira is in go-gerrit:

https://github.com/andygrunwald/go-gerrit/blob/master/authentication.go

I don't think he would mind if you created a pull request to fix the problem.

**Comment by perolausson** [comment]
There is also an example in that project on how to use it.

https://github.com/andygrunwald/go-gerrit#http-basic

**Comment by andygrunwald** [comment]
One alternative would be ` jiraClient, _ := jira.NewClient(nil, "https://user:pass@issues.apache.org/jira/")` (when i get it correct).

Otherwise i would be happy about a PR.

**Comment by fkrauthan** [comment]
I will look into creating a PR for this.

**Comment by andygrunwald** [comment]
Fixed in #62 
Thank you @fkrauthan. @perolausson and @Smadarl
