### ISSUE TITLE
Use Personal Access Tokens instead of username and password

### ISSUE THREAD

**Issue by fabriziopandini** [andygrunwald/go-jira#641]
## What would you like to be added?
I would like to use Personal Access Tokens instead of username and password to access Jira

## Why is this needed?
According to Jira documentation
> Personal access tokens are a safe alternative to using username and password for authentication with various services. 

https://confluence.atlassian.com/enterprise/using-personal-access-tokens-1026032365.html

## Anything else we need to know?
If you give me some pointers, I can try to contribute this feature

And thanks for developing and maintaining this project!

**Comment by vladimir-ch** [comment]
This already exists, see `onpremise/examples/bearerauth/main.go` on the main branch.

**Comment by fabriziopandini** [comment]
Worked like a charm!
Awesome project!
