### ISSUE TITLE
Question: get all project issues

### ISSUE THREAD

**Issue by gguimaraesbr** [andygrunwald/go-jira#66]
Is it possible to get all the issues for a given project without providing a sprint id?

**Comment by andygrunwald** [comment]
Hey @gguimaraesbr,

i guess it is the same question like https://github.com/andygrunwald/go-jira/issues/59#issuecomment-275920497, isn' it?
Might the code snipped in issue #59 help?

**Comment by gguimaraesbr** [comment]
Hi @andygrunwald,

I was looking for something like `func (s *IssueService) GetIssues(projectkey string) ([]Issue, error)`, if it make any sense, but I think the `jql` approach will do the job.

Best.

**Comment by andygrunwald** [comment]
Hey @gguimaraesbr,
this would also be an option, but this is not implemented yet.
Feel free to create this function and apply a PR. I would be happy to merge it.

**Comment by gguimaraesbr** [comment]
Hi, @andygrunwald 

I still need to find out how to handle with `startAt` and `maxResults` in that scenario.
