### ISSUE TITLE
Create Issue with customfields

### ISSUE THREAD

**Issue by rogerwelin** [andygrunwald/go-jira#67]
How can I create a jira.Issue that has customfields described in IssueFields? Is that supported?

**Comment by andygrunwald** [comment]
Hey @rogerwelin,
this question was answered in https://github.com/andygrunwald/go-jira/issues/35 some time ago.
Would you mind to check this ticket out and if this helps you?

**Comment by andygrunwald** [comment]
No feedback since one week. @rogerwelin If this don't work, please reopen this ticket and let me know.

**Comment by ketanmujumdar** [comment]
Hello @andygrunwald Can I have a real world example for the same ? Sorry but I am new to golang.

**Comment by andygrunwald** [comment]
You can use the [InitIssueWithMetaAndFields](https://godoc.org/github.com/andygrunwald/go-jira#InitIssueWithMetaAndFields) function.
See here for a real world example: https://github.com/cloudflare/complainer/blob/master/reporter/jira.go#L125

Does this help?
