### ISSUE TITLE
attachmentID method parameter name misleading

### ISSUE THREAD

**Issue by AdamJacobMuller** [andygrunwald/go-jira#70]
Hi,
I was looking for how to add an attachment to an issue and I saw:
https://github.com/andygrunwald/go-jira/blob/master/issue.go#L519

But I spent a bunch of time trying to figure out how to create an attachmentID, it would probably be more obvious if this was renamed "issueID" or "issueKey" ?

This shouldn't break/change the API at all, so if others think its a good idea I can submit a PR for this?

-Adam

**Comment by andygrunwald** [comment]
Hey @AdamJacobMuller,

yes. Make sense. Feel free :)

**Comment by andygrunwald** [comment]
Already done in https://github.com/andygrunwald/go-jira/commit/88bab6c4c87e924fabae656481021437d9370045
Thanks to @francoishill
