### ISSUE TITLE
Improve error handling to manage unexpected JIRA responses

### ISSUE THREAD

**Issue by Kegsay** [andygrunwald/go-jira#8]
The JIRA client library supports making arbitrary REST API calls to JIRA. This is great. However, not all of JIRA expresses errors as `ErrorResponse` JSON objects. Innocently missing parameters in some requests can make JIRA fail ungracefully with an XML response containing a Java stack trace. This *would* be fine, if it weren't for https://github.com/andygrunwald/go-jira/blob/22e19893f5e074082091e116f816bb7b8f320467/jira.go#L119 

As a result of this, the response body, which contains vital information when trying to wrangle JIRA's REST API, is lost to the caller. This is made even worse by the fact that the caller *cannot manually read the response body* because it has already been read and closed.

Given the API contract for this is to return a generic `error` and callers are expected to type assert for `ErrorResponse`, I would be tempted to add either an `UnhandledErrorResponse` type, or just shove the response body into Go's default `error` type. This then allows the caller to at least debug problems with their REST API calls.

**Comment by andygrunwald** [comment]
Hey @Kegsay,

thank you for your issue. You are totally right.
Do you have an example URL where a XML response + a XML stack trace is given as a response?
Such an URL can be used to implement this behaviour.

Is this an URL you are reffering to? https://issues.apache.org/jira/rest/api/2/issue/sss/MESOS-3325
Or do you have a better example?

**Comment by Kegsay** [comment]
That's a good example of JIRA returning XML responses on errors. I've seen similar looking ones which return `HTTP 500`, for example when `POST`ing to  `/rest/webhooks/1.0/webhook` with most but not all of the required fields.

I'm not sure how public-facing these error responses are supposed to be - so I would be hesitant trying to design a `struct` which can handle all of these responses, because we may not have any guarantees that JIRA will always return them in that format.

**Comment by andygrunwald** [comment]
Thank you @Kegsay!
I thought a little bit about this. You are true. It would be a waste of time + never complete to design a data structure to  parse each error.
I dropped the `ErrorResponse` type at all. The caller is now responsible to analyze the response body and parse it (if needed).

Here is a small snippet for testing:
```go
package main

import (
	"fmt"
	"github.com/andygrunwald/go-jira"
	"io/ioutil"
)

func main() {
	jiraClient, _ := jira.NewClient(nil, "https://issues.apache.org/jira/")
	req, _ := jiraClient.NewRequest("POST", "rest/webhooks/1.0/webhook", nil)

	r, err := jiraClient.Do(req, nil)
	if err != nil {
		fmt.Printf("Request Error: %s\n", err)
	}

	data, err := ioutil.ReadAll(r.Body)
	if err != nil {
		fmt.Printf("Read Error: %s\n", err)
	}

	fmt.Printf("%+v\n", string(data))
}
```

Result:
```
Request Error: Request failed. Please analyze the request body for more details. Status code: 401
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><status><status-code>401</status-code><message>Client must be authenticated to access this resource.</message></status>
```

**Comment by Kegsay** [comment]
Looks good to me :) thanks!
