### ISSUE TITLE
No Data Returned

### ISSUE THREAD

**Issue by fii** [andygrunwald/go-jira#80]
Hello, 

We're running this based on the examples provided but no data is being returned: 

Here's the script 

Thanks

**Comment by andygrunwald** [comment]
Hey @fii,

which JIRA Version you are using?
Do you have any way how i can reproduce this? Can you test this against a public JIRA like the Apache one?

**Comment by andygrunwald** [comment]
No feedback since ~2 month.
If this issue is still present or if you can provide more information (like how i can reproduce this issue, docker image, jira version, etc.), please reopen it.
