### ISSUE TITLE
Support gopkg.in

### ISSUE THREAD

**Issue by pavel-at-getpatch** [andygrunwald/go-jira#81]
Please support linking this library with gopkg.in by making current state as v1 by tagging or branhing.
More info here: http://labix.org/gopkg.in

**Comment by andygrunwald** [comment]
Thanks @pavel-at-getpatch for this suggestion.
I tagged a https://github.com/andygrunwald/go-jira/tree/v1.0.0 version and added a small note in the README. See https://github.com/andygrunwald/go-jira/commit/e844092bb379d40732b5f43be646d4ac88790eab

You know can import it via `gopkg.in/andygrunwald/go-jira.v1`

Have fun!
